<?php

namespace App\Support;

/**
 * Catalogul Bibliotecii online (migrare columna.org.md → columna.md).
 * Generat automat din pagina veche. Linkurile țintesc fișierele existente
 * (folderul server `/biblioteca/`); la mutarea domeniului se copiază server-side
 * în public/downloads/biblioteca/ și se repointează URL-urile.
 */
final class BibliotecaLibrary
{
    /**
     * @return list<array{title: string, books: list<array{title: string, url: string}>}>
     */
    public static function categories(): array
    {
        return [
            [
                'title' => 'Literatura Română',
                'books' => [
                    ['title' => 'Agârbiceanu, Ion — Fefeleaga', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Agarbiceanu-Ion-Fefeleaga.pdf'],
                    ['title' => 'Alecsandri, Vasile — Poezii populare ale românilor', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/alecs_poez_pop.pdf'],
                    ['title' => 'Alecsandri, Vasile — Înşiră-te, mărgărite', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Insira-te-margarite.pdf'],
                    ['title' => 'Alecsandri, Vasile — Chiriţa în Iaşi sau două fete ş-o neneacă', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/VasileAlexandri-ChiritainIasi.pdf'],
                    ['title' => 'Alecsandri, Vasile — Balta-Albă, Proză literară', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/v_alecs2.pdf'],
                    ['title' => 'Alecsandri, Vasile — Comedii şi drame', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/v_alecs3.pdf'],
                    ['title' => 'Alecsandri, Vasile — Sânziana şi Pepelea', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/alecs_sanz.pdf'],
                    ['title' => 'Alecsandri, Vasile — Rusaliile', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/alecs_rus.pdf'],
                    ['title' => 'Alecsandri, Vasile — Muntele de foc', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Alecsandri-Vasile-Muntele-de-foc.pdf'],
                    ['title' => 'Alecsandri, Vasile — Despot Vodă', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Despot-Voda.pdf'],
                    ['title' => 'Alexandrescu, Grigore — Poezii şi proză', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/alexandrescu.pdf'],
                    ['title' => 'Arghezi, Tudor — Poezii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Arghezi_Poezii.pdf'],
                    ['title' => 'Asachi, Gheorghe — Dochia şi Traian', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/asachi.pdf'],
                    ['title' => 'Asachi, Gheorghe — Ode, elegii, sonete', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/asachi_opere.pdf'],
                    ['title' => 'Asachi, Gheorghe — Cântul cignului', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Asachi_Cantul_cignului.pdf'],
                    ['title' => 'Bacovia, George — Plumb', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Bacovia_Plumb.pdf'],
                    ['title' => 'Bacovia, George — Poezii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/bacovia.pdf'],
                    ['title' => 'Bacovia, George — Ştanţe burgheze, poezii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/bacovia_st_burgh.pdf'],
                    ['title' => 'Basarab, Neagoe — Învăţăturile lui Neagoe Basarab către fiul său Theodosie', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/basarab_invataturi.pdf'],
                    ['title' => 'Blaga, Lucian — Poemele luminii, poezii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/blaga_poeme.pdf'],
                    ['title' => 'Blaga, Lucian — În marea trecere, poezii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/blaga_1924.pdf'],
                    ['title' => 'Blaga, Lucian — În cumpăna apelor, poezii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/blaga_1933.pdf'],
                    ['title' => 'Blaga, Lucian — Poezii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/blaga.pdf'],
                    ['title' => 'Blaga, Lucian — Spaţiul mioritic', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/blaga_spat_miorit.pdf'],
                    ['title' => 'Blaga, Lucian — Orizont şi stil', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/blaga_orizont.pdf'],
                    ['title' => 'Blandiana, Ana — Geniul de a fi', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Blandiana_Geniul_de_a_fi.pdf'],
                    ['title' => 'Blandiana, Ana — La cules de îngeri', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Blandiana_La_cules_de_ingeri.pdf'],
                    ['title' => 'Boliac, Cezar — Poezii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/boliac.pdf'],
                    ['title' => 'Bolintineanu, Dimitrie — Legende istorice (versuri)', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/bolintineanu.pdf'],
                    ['title' => 'BP Hașdeu — Micuta', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/bph_micuta.pdf'],
                    ['title' => 'BP Hașdeu — Muntele şi valea', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/bph_2.pdf'],
                    ['title' => 'BP Hașdeu — Poezie, proză, dramaturgie', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/bph_1.pdf'],
                    ['title' => 'Budai Deleanu, Ion — Ţiganiada', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Budai-Deleanu_Tiganiada.pdf'],
                    ['title' => 'Busuioc, Aureliu — Pactizând cu diavolul', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Diavol.pdf'],
                    ['title' => 'Cârlova, Vasile — Poezii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/poezii.pdf'],
                    ['title' => 'Călinescu, George — Istoria literaturii române', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Calinescu_Istoria_literaturii.pdf'],
                    ['title' => 'Călinescu, George — Enigma Otiliei', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/GeorgeCalinescu-EnigmaOtiliei.pdf'],
                    ['title' => 'Călinescu, George — Viaţa şi opera lui Ion Creangă', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Calinescu George - Viata si opera lui Ion Creanga (Cartea).pdf'],
                    ['title' => 'Călinescu, George — Viaţa lui Mihai Eminescu', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/George Calinescu - Viata lui Mihai Eminescu.pdf'],
                    ['title' => 'Cantacuzino, Constantin — Istoria Țării Românești', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Cantacuzino C-tin - Istoria tarii romanesti (Cartea).pdf'],
                    ['title' => 'Cantemir, Dimitrie — Descrierea Moldovei', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/cantemir_dimitrie___descrierea_mold_(cartea).pdf'],
                    ['title' => 'Caragiale, Ion Luca — D-l Goe... şi alţii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/dl_goe.pdf'],
                    ['title' => 'Caragiale, Ion Luca — Istoria se repetă', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Ion Luca Caragiale - Istoria se repeta.pdf'],
                    ['title' => 'Caragiale, Ion Luca — În vreme de război', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/vreme.pdf'],
                    ['title' => 'Caragiale, Ion Luca — O noapte furtunoasă', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/I.L.Caragiale-Onoaptefurtunoasa.pdf'],
                    ['title' => 'Caragiale, Ion Luca — Conu Leonida faţă cu reacţiunea', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/I.L.Caragiale-ConuLeonidafatacureact.pdf'],
                    ['title' => 'Caragiale, Ion Luca — O scrisoare pierdută', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/I.L.Caragiale-Oscrisoarepierduta.pdf'],
                    ['title' => 'Caragiale, Ion Luca — Năpasta', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/I.L.Caragiale-Napasta.pdf'],
                    ['title' => 'Caragiale, Ion Luca — O soacră, farsă fantezistă într-un act', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/soacra.pdf'],
                    ['title' => 'Caragiale, Ion Luca — O făclie de Paşte', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/I.L.Caragiale - O faclie de pasti.pdf'],
                    ['title' => 'Caragiale, Ion Luca — Remember', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/caragiale_rem.pdf'],
                    ['title' => 'Caragiale, Ion Luca — Parodii în versuri şi proză', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/caragiale_parodii.pdf'],
                    ['title' => 'Caragiale, Mateiu — Craii de Curtea-Veche', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Caragiale Mateiu - Craii de curte veche (Cartea).pdf'],
                    ['title' => 'Coșbuc, George — Fire de tort', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/cosbuc2.pdf'],
                    ['title' => 'Coșbuc, George — Cântece de vitejie', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/cosbuc1.pdf'],
                    ['title' => 'Costin, Miron — Letopiseţul Ţării Moldovei', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/MironCostin-LetopisetultariiMoldovei.pdf'],
                    ['title' => 'Creangă, Ion — Poveşti', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/IonCreanga-Povesti.pdf'],
                    ['title' => 'Creangă, Ion — Povestiri', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/IonCreanga-Povestiri.pdf'],
                    ['title' => 'Creangă, Ion — Scrieri', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/creanga_scr.pdf'],
                    ['title' => 'Creangă, Ion — Amintiri din copilărie', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/IonCreanga-Amintiridincopilarie.pdf'],
                    ['title' => 'DICȚIONARE — Dicționar de proverbe și zicători românești', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Dictionar Proverbe (Cartea).pdf'],
                    ['title' => 'DICȚIONARE — Dicționar ortografic al limbii române', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/DOR pt elevi (Cartea).pdf'],
                    ['title' => 'Donici, Alecu — Scrieri', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/donici_scrieri.pdf'],
                    ['title' => 'Dosoftei — Psalmul 136', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/dosoftei.pdf'],
                    ['title' => 'Eliade, Mircea — Maitreyi', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Mircea Eliade - Maitreyi.pdf'],
                    ['title' => 'Eliade, Mircea — La ţigănci', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/eliade.pdf'],
                    ['title' => 'Eliade, Mircea — Domnişoara Cristina', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Mircea+Eliade+-+Domnisoara+Christina.pdf'],
                    ['title' => 'Eliade, Mircea — Secretul doctorului Honigberger', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/meliade_secret.pdf'],
                    ['title' => 'Eliade, Mircea — Salazar', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/meliade_salazar.pdf'],
                    ['title' => 'Eminescu, Mihai — Poezii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/MihaiEminescu-Poezii.pdf'],
                    ['title' => 'Eminescu, Mihai — Versuri lirice, Opera poetică', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/emin_vers_lir.pdf'],
                    ['title' => 'Eminescu, Mihai — Luceafărul, Antume', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Mihai Eminescu - Luceafarul.pdf'],
                    ['title' => 'Eminescu, Mihai — Memento mori, Postume', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Eminescu Mihai - Memento Mori (volum postume).pdf'],
                    ['title' => 'Eminescu, Mihai — Sărmanul Dionis', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/sarmanul dionis.pdf'],
                    ['title' => 'Eminescu, Mihai — Proze antume', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/MihaiEminescu-proze_antume.pdf'],
                    ['title' => 'Eminescu, Mihai — Proze postume', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/MihaiEminescu-proze_postume.pdf'],
                    ['title' => 'Eminescu, Mihai — George Călinescu, Viaţa lui Mihai Eminescu', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/George Calinescu - Viata lui Mihai Eminescu.pdf'],
                    ['title' => 'Eminescu, Mihai — Titu Liviu Maiorescu, Eminescu şi poeziile lui', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/zburatorul.pdf'],
                    ['title' => 'Eminescu, Mihai — D. Panaitescu Perpessicius, Studii eminesciene', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/perspessicius_emin.pdf'],
                    ['title' => 'Eminescu, Mihai — Scrieri politice', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/emin_scr_polit.pdf'],
                    ['title' => 'Eminescu, Mihai — Radu Mihai Crişan, Eminescu interzis. Gândirea politică', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/eminescu_interzis_gandirea_politica.pdf'],
                    ['title' => 'Esinencu, Nicolae — Copacul care ne uneşte', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/esinencu.pdf'],
                    ['title' => 'Goga, Octavian — Ne cheamă pământul', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Octavian Goga - Ne cheama pamantul.pdf'],
                    ['title' => 'Goma, Paul — Basarabia', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma.pdf'],
                    ['title' => 'Goma, Paul — Din calidor, o copilărie basarabeană', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_din_calidor.pdf'],
                    ['title' => 'Goma, Paul — Sabina', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_sabina.pdf'],
                    ['title' => 'Goma, Paul — Uşa noastră cea de toate zilele', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_usa.pdf'],
                    ['title' => 'Goma, Paul — Alfabecedar', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_alfa.pdf'],
                    ['title' => 'Goma, Paul — Altina, Grădina scufundată', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_altina.pdf'],
                    ['title' => 'Goma, Paul — Un fals pentru eternitate', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_tratat.pdf'],
                    ['title' => 'Goma, Paul — Justa', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_justa.pdf'],
                    ['title' => 'Goma, Paul — Lista lui Vasile Paraschiv', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_lista.pdf'],
                    ['title' => 'Goma, Paul — Ela', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_ela.pdf'],
                    ['title' => 'Goma, Paul — Cod "Bărbosul", din dosarele de securitate 1957-1977', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_cod.pdf'],
                    ['title' => 'Goma, Paul — Patimile după Piteşti', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_patim.pdf'],
                    ['title' => 'Goma, Paul — Amnezia la români', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_amnezia.pdf'],
                    ['title' => 'Goma, Paul — Anticultura', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_anticultura.pdf'],
                    ['title' => 'Goma, Paul — Bătrânul şi fata', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_batr.pdf'],
                    ['title' => 'Goma, Paul — Bonifacia', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_bonifacia.pdf'],
                    ['title' => 'Goma, Paul — Gherla. Lătineşti', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_gherla.pdf'],
                    ['title' => 'Goma, Paul — Arta refugii, o copilărie transilvaneană', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_arta.pdf'],
                    ['title' => 'Goma, Paul — Sus, în vârful Raiului', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_sus.pdf'],
                    ['title' => 'Goma, Paul — Soldatul câinelui', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_sold.pdf'],
                    ['title' => 'Goma, Paul — Săptămâna roşie', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_sapt.pdf'],
                    ['title' => 'Goma, Paul — Roman intim', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_roman.pdf'],
                    ['title' => 'Goma, Paul — Profilul', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_profil.pdf'],
                    ['title' => 'Goma, Paul — Infarct', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_infarct.pdf'],
                    ['title' => 'Goma, Paul — Nota biografică', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/goma_biogr.pdf'],
                    ['title' => 'Heliade-Rădulescu, Ion — Zburătorul', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/zburatorul_Heliade.pdf'],
                    ['title' => 'Heliade-Rădulescu, Ion — Spiritul critic în cultura românească', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Ibraileanu Garabet - Spiritul critic in cultura rom.pdf'],
                    ['title' => 'Ionescu, Eugen — Englezeşte fără profesor', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/englezeste.pdf'],
                    ['title' => 'Ionescu, Eugen — Cântăreaţa cheală', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/cantareata.pdf'],
                    ['title' => 'Ionescu, Eugen — Rinocerii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/rinocerii.pdf'],
                    ['title' => 'Ionescu, Eugen — Regele moare', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/regele.pdf'],
                    ['title' => 'Ionescu, Eugen — Delir în doi. Şi-n câţi vrei', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/delir.pdf'],
                    ['title' => 'Isanos, Magda — Poezii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/isanos.pdf'],
                    ['title' => 'Ispirescu, Petre — Legendele sau basmele românilor', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/PetreIspirescu-Basmeleromanilor.pdf'],
                    ['title' => 'Istrati, Panait — Ciulinii bărăganului', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Panait Istrati - Ciulinii Baraganului.pdf'],
                    ['title' => 'Istrati, Panait — Chira Chiralina', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Panait Istrati - Chira Chiralina.pdf'],
                    ['title' => 'Kogălniceanu, Mihail — Scrieri literare', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/MihailKogalniceanu-Scrieriliterare.pdf'],
                    ['title' => 'Labiș, Nicolae — Moartea căprioarei', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Labis Nicolae - Moartea caprioarei (volum poezii).pdf'],
                    ['title' => 'Matcovschi, Dumitru — Vad', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/matcovschi_vad.pdf'],
                    ['title' => 'Mateevici, Alexei — Poezii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/mateevici.pdf'],
                    ['title' => 'Minulescu, Ion — Nu sunt ce par a fi', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Minulescu Ion - Nu sunt ce par a fi (volum poezii).pdf'],
                    ['title' => 'Minulescu, Ion — Roşu, galben şi albastru', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Minulescu, Ion - Rosu, galben si albastru.pdf'],
                    ['title' => 'Mioara, Avram — Ortografie pentru toţi', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Avram Mioara - Ortografie pentru toti (Cartea).pdf'],
                    ['title' => 'Mitru, Alexandru — Poveşti despre Păcală şi Tîndală', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/mitru.pdf'],
                    ['title' => 'Neculce, Ion — Letopiseţul Ţării Moldovei', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/neculce.pdf'],
                    ['title' => 'Negruzzi, Costache — Negru pe alb', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/negruzzi.pdf'],
                    ['title' => 'Noica, Constantin — Mathesis sau bucuriile simple', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Constantin Noica - Mathesis sau bucuriile simple.pdf'],
                    ['title' => 'Noica, Constantin — De Caelo, Încercare în jurul cunoaşterii şi individului', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Constantin Noica - De Caelo.pdf'],
                    ['title' => 'Noica, Constantin — Modelul cultural european', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/NOIC_MCE.pdf'],
                    ['title' => 'Odobescu, Alexandru — Doamna Chiajna și alte proze', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Odobescu Alexandru - Doamna Chiajna (Cartea).pdf'],
                    ['title' => 'Pann, Anton — Povestea vorbii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Pann Anton - Povestea vorbii.pdf'],
                    ['title' => 'Petrescu, Camil — Ultima noapte de dragoste, întâia noapte de război', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Ultima noapte de dragoste, intiia noapte de razboi - Camil Petrescu.pdf'],
                    ['title' => 'POPULARE — Mioriţa', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/miorita.pdf'],
                    ['title' => 'POPULARE — Dorin Ştef, Mioriţa colind, Analiza variantelor din nordul Transilvaniei', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/miorita_analiza.pdf'],
                    ['title' => 'POPULARE — Dorin Ştef, Mioriţa în Maramureş, Tipologia variantelor din Maramureş', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/miorita_analiza2.pdf'],
                    ['title' => 'POPULARE — Monăstirea Argeşului', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/monarg.pdf'],
                    ['title' => 'POPULARE — Cărți populare românești', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Carti populare romanesti (Cartea).pdf'],
                    ['title' => 'Preda, Marin — Viaţa ca o pradă', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/preda_vcp.pdf'],
                    ['title' => 'Preda, Marin — Imposibila întoarcere', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/preda_imposibila_intoarcere.pdf'],
                    ['title' => 'Rebreanu, Liviu — Ciulendra, Catastrofa şi alte nuvele', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/LiviuRebreanu-Ciuleandra.pdf'],
                    ['title' => 'Rebreanu, Liviu — Adam şi Eva', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/liviu_ada_eva.pdf'],
                    ['title' => 'Rebreanu, Liviu — Pădurea spânzuraţilor', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Liviu Rebreanu - Padurea spanzuratilor.pdf'],
                    ['title' => 'Russo, Alecu — Cântarea României', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/russo.pdf'],
                    ['title' => 'Sadoveanu, Mihail — Ţara de dincolo de negură', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/MihailSadoveanu-Taradedincolodenegur.pdf'],
                    ['title' => 'Slavici, Ioan — Poveşti', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/IoanSlavici-Povesti.pdf'],
                    ['title' => 'Slavici, Ioan — Nuvele', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/IoanSlavici - Nuvele.pdf'],
                    ['title' => 'Slavici, Ioan — Mara', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/IoanSlavici-Mara.pdf'],
                    ['title' => 'Slavici, Ioan — Moara cu noroc', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Slavici Ioan - Moara cu noroc (Cartea).pdf'],
                    ['title' => 'Sorescu, Marin — Poezii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/sorescu_poez.pdf'],
                    ['title' => 'Sorescu, Marin — Iona', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Marin Sorescu - IONA.pdf'],
                    ['title' => 'Stănescu, Nichita — Argonica, poezii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/NichitaStanescu-Argonice.pdf'],
                    ['title' => 'Stănescu, Nichita — Epica magna, poezii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/stanescu.pdf'],
                    ['title' => 'Topârceanu, George — Balade vesele şi triste', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Toparceanu G - Balade vesele si triste.pdf'],
                    ['title' => 'Topârceanu, George — Migdale amare', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/toparc_migdale.pdf'],
                    ['title' => 'Topârceanu, George — Parodii originale', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/toparc_parodii.pdf'],
                    ['title' => 'Topârceanu, George — Cocostârcul albastru', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/George Toparceanu - Cocostarcul albastru.pdf'],
                    ['title' => 'Topârceanu, George — Postume', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/toparc_postume.pdf'],
                    ['title' => 'Ureche, Grigore — Letopiseţul Ţării Moldovei', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/ureche_letopiset.pdf'],
                    ['title' => 'Vieru, Grigore — Acum și în veac', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/gv_1.pdf'],
                    ['title' => 'Vlahuță, Alexandru — Din trecutul nostru, România pitorească', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Vlahuta Alexandru- Din trecutul nostru (proza istorica).pdf'],
                    ['title' => 'Vlahuță, Alexandru — Iubire, volum de poezii', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Vlahuta Alexandru - Iubire (volum poezii).pdf'],
                    ['title' => 'Zamfirescu, Duiliu — Viața la țară', 'url' => 'https://columna.org.md/biblioteca/literatura-romana/Zamfirescu Duiliu - Viata la tara (Cartea).pdf'],
                ],
            ],
            [
                'title' => 'Curriculum (2019)',
                'books' => [
                    ['title' => 'Informatică , curriculumul actualizat pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/info_c_l_2019.pdf'],
                    ['title' => 'Matematică , curriculumul actualizat pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/mate_c_l_2019.pdf'],
                    ['title' => 'Matematică , curriculumul actualizat pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/mate_c_g_2019.pdf'],
                    ['title' => 'Informatică , curriculumul actualizat pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/info_c_g_2019.pdf'],
                    ['title' => 'Biologie , curriculumul actualizat pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/bio_c_l_2019.pdf'],
                    ['title' => 'Biologie , curriculumul actualizat pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/bio_c_g_2019.pdf'],
                    ['title' => 'Chimie , curriculumul actualizat pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/chim_c_l_2019.pdf'],
                    ['title' => 'Chimie , curriculumul actualizat pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/chim_c_g_2019.pdf'],
                    ['title' => 'Limba şi literatura română , curriculumul actualizat pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/rom_c_l_2019.pdf'],
                    ['title' => 'Limba şi literatura română , curriculumul actualizat pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/rom_c_g_2019.pdf'],
                    ['title' => 'Istorie , curriculumul actualizat pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/ist_c_l_2019.pdf'],
                    ['title' => 'Istorie , curriculumul actualizat pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/ist_c_g_2019.pdf'],
                    ['title' => 'Geografie , curriculumul actualizat pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/geo_c_g_2019.pdf'],
                    ['title' => 'Fizică , curriculumul actualizat pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/fiz_c_l_2019.pdf'],
                    ['title' => 'Fizică , curriculumul actualizat pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/fiz_c_g_2019.pdf'],
                    ['title' => 'Educaţie fizică , curriculumul actualizat pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/edfiz_c_l_2019.pdf'],
                    ['title' => 'Educaţie fizică , curriculumul actualizat pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/edfiz_c_g_2019.pdf'],
                    ['title' => 'Literatura universală , curriculumul actualizat pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/litun_c_l_2019.pdf'],
                    ['title' => 'Limba rusă , curriculumul actualizat pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/rusa_c_g_2019.pdf'],
                    ['title' => 'Limba străină , curriculumul actualizat pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/str_c_g_2019.pdf'],
                    ['title' => 'Limba străină , curriculumul actualizat pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/str_c_l_2019.pdf'],
                    ['title' => 'Ştiinţe , curriculumul actualizat pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/st_c_g_2019.pdf'],
                    ['title' => 'Educaţie plastică , curriculumul actualizat pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/edpl_c_g_2019.pdf'],
                    ['title' => 'Educaţie muzicală , curriculumul actualizat pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum-2019/edmuz_c_g_2019.pdf'],
                ],
            ],
            [
                'title' => 'Ghiduri de implementare a curriculumului (2019)',
                'books' => [
                    ['title' => 'Matematica , ghid de implementare a curriculumului actualizat pentru clasele X-XII', 'url' => 'https://columna.org.md/biblioteca/ghiduri/mate_gh_l_2019.pdf'],
                    ['title' => 'Matematica , ghid de implementare a curriculumului actualizat pentru clasele V-IX', 'url' => 'https://columna.org.md/biblioteca/ghiduri/mate_gh_g_2019.pdf'],
                    ['title' => 'Biologie , ghid de implementare a curriculumului actualizat pentru clasele X-XII', 'url' => 'https://columna.org.md/biblioteca/ghiduri/bio_gh_l_2019.pdf'],
                    ['title' => 'Biologie , ghid de implementare a curriculumului actualizat pentru clasele VI-IX', 'url' => 'https://columna.org.md/biblioteca/ghiduri/bio_gh_g_2019.pdf'],
                    ['title' => 'Chimie , ghid de implementare a curriculumului actualizat pentru clasele X-XII', 'url' => 'https://columna.org.md/biblioteca/ghiduri/chim_gh_l_2019.pdf'],
                    ['title' => 'Chimie , ghid de implementare a curriculumului actualizat pentru clasele VII-IX', 'url' => 'https://columna.org.md/biblioteca/ghiduri/chim_gh_g_2019.pdf'],
                    ['title' => 'Fizică , ghid de implementare a curriculumului actualizat pentru clasele VI-IX', 'url' => 'https://columna.org.md/biblioteca/ghiduri/fiz_gh_g_2019.pdf'],
                    ['title' => 'Fizică , ghid de implementare a curriculumului actualizat pentru clasele X-XII', 'url' => 'https://columna.org.md/biblioteca/ghiduri/fiz_gh_l_2019.pdf'],
                    ['title' => 'Informatică , ghid de implementare a curriculumului actualizat pentru clasele X-XII', 'url' => 'https://columna.org.md/biblioteca/ghiduri/info_gh_l_2019.pdf'],
                    ['title' => 'Informatică , ghid de implementare a curriculumului actualizat pentru clasele VII-IX', 'url' => 'https://columna.org.md/biblioteca/ghiduri/info_gh_g_2019.pdf'],
                    ['title' => 'Istorie , ghid de implementare a curriculumului actualizat pentru clasele V-IX', 'url' => 'https://columna.org.md/biblioteca/ghiduri/ist_gh_g_2019.pdf'],
                    ['title' => 'Literatura universală , ghid de implementare a curriculumului actualizat pentru clasele X-XII', 'url' => 'https://columna.org.md/biblioteca/ghiduri/litun_gh_l_2019.pdf'],
                    ['title' => 'Limba și literatura română , ghid de implementare a curriculumului actualizat pentru clasele X-XII', 'url' => 'https://columna.org.md/biblioteca/ghiduri/rom_gh_l_2019.pdf'],
                    ['title' => 'Limba și literatura română , ghid de implementare a curriculumului actualizat pentru clasele V-IX', 'url' => 'https://columna.org.md/biblioteca/ghiduri/rom_gh_g_2019.pdf'],
                    ['title' => 'Limba rusă , ghid de implementare a curriculumului actualizat pentru clasele V-IX', 'url' => 'https://columna.org.md/biblioteca/ghiduri/rusa_gh_g_2019.pdf'],
                    ['title' => 'Științe , ghid de implementare a curriculumului actualizat pentru clasa a V-a', 'url' => 'https://columna.org.md/biblioteca/ghiduri/st_gh_g_2019.pdf'],
                    ['title' => 'Limba străină , ghid de implementare a curriculumului actualizat pentru clasele V-IX', 'url' => 'https://columna.org.md/biblioteca/ghiduri/str_gh_g_2019.pdf'],
                    ['title' => 'Limba străină , ghid de implementare a curriculumului actualizat pentru clasele X-XII', 'url' => 'https://columna.org.md/biblioteca/ghiduri/str_gh_l_2019.pdf'],
                ],
            ],
            [
                'title' => 'Repere metodologice privind organizarea procesului educațional în anul de studii 2023-2024',
                'books' => [
                    ['title' => 'Repere metodologice privind organizarea procesului educațional la disciplina matematică în anul de studii 2023-2024', 'url' => 'https://columna.org.md/wp-content/uploads/2023/10/10_repere_matematica_2023-2024_ro_final_pt_site.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional la disciplina școlară geografie în anul de studii 2023-2024', 'url' => 'https://columna.org.md/wp-content/uploads/2023/10/21_repere_geografie_2023-2024_final_pt_site.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional la disciplina școlară istoria românilor și universală în anul de studii 2023-2024', 'url' => 'https://columna.org.md/wp-content/uploads/2023/10/20_repere_istoria_rom_si_unuiversala_iru_2023-2024_final_pt_site.pdf'],
                    ['title' => 'Repere metodologice privind organizarea procesului educațional la limba străină în anul de studii 2023-2024', 'url' => 'https://columna.org.md/wp-content/uploads/2023/10/4_repere_metodologice_lstraina_2023-2024_final_poe_site.pdf'],
                    ['title' => 'Repere metodologice privind organizarea procesului educațional la limba și literatura română în anul de studii 2023-2024', 'url' => 'https://columna.org.md/wp-content/uploads/2023/10/2_repere_metodologice_l.rom_._sc.nat_._2023-2024_final_pe_site.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional în învățământul primar în anul de studii 2023-2024', 'url' => 'https://columna.org.md/wp-content/uploads/2023/10/17_repere_invat._primar_sm_primar_2023-2024_final_pt_site.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional la chimie în anul de studii 2023-2024', 'url' => 'https://columna.org.md/wp-content/uploads/2023/10/11_chimie-repere_metodologice-2023-2024_ro_final_pt_site.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional la biologie în anul de studii 2023-2024', 'url' => 'https://columna.org.md/wp-content/uploads/2023/10/12_repere_metodol._biologie_ro_2023-2024_final_pt_site_0.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional la informatică în anul de studii 2023-2024', 'url' => 'https://columna.org.md/wp-content/uploads/2023/10/23_repere_metodologice_informatica_2023-2024_final_pt_site.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional la fizică în anul de studii 2023-2024', 'url' => 'https://columna.org.md/wp-content/uploads/2023/10/18_fizica_repere_metodologice_ro2023-2024_final_pt_site.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional la educație pentru societate în anul de studii 2023-2024', 'url' => 'https://columna.org.md/wp-content/uploads/2023/10/22_repere_educatie_pentru_societate_eps_2023-2024_final_pt_site.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional la educație fizică în anul de studii 2022-2023', 'url' => 'https://columna.org.md/biblioteca/repere/23_educatie_fizica_2022-2023_final.pdf'],
                ],
            ],
            [
                'title' => 'Repere metodologice privind organizarea procesului educațional în anul de studii 2022-2023',
                'books' => [
                    ['title' => 'Repere metodologice privind organizarea procesului educațional la disciplina matematică în anul de studii 2022-2023', 'url' => 'https://columna.org.md/biblioteca/repere/11_repere_metod_matem_ro_2022_2023_ff.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional la disciplina școlară geografie în anul de studii 2022-2023', 'url' => 'https://columna.org.md/biblioteca/repere/geofragie_repere_metodologice_2022-2023_ro_0.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional la disciplina școlară istoria românilor și universală în anul de studii 2022-2023', 'url' => 'https://columna.org.md/biblioteca/repere/isoria_romanilor_si_universala_repere_metodologice_2022-2023-ro_1.pdf'],
                    ['title' => 'Repere metodologice privind organizarea procesului educațional la limba străină în anul de studii 2022-2023', 'url' => 'https://columna.org.md/biblioteca/repere/repere_metodologice_l.straina_2022-2023_final.pdf'],
                    ['title' => 'Repere metodologice privind organizarea procesului educațional la limba și literatura română în anul de studii 2022-2023', 'url' => 'https://columna.org.md/biblioteca/repere/repere_metodologice_l.rom._sc.nat._2022-2023_final.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional în învățământul primar în anul de studii 2022-2023', 'url' => 'https://columna.org.md/biblioteca/repere/2_invatamant_primar_sm_primar_2022-2023_final_0.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional la chimie în anul de studii 2022-2023', 'url' => 'https://columna.org.md/biblioteca/repere/14_chimie_ro_2022-2023_final.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional la biologie în anul de studii 2022-2023', 'url' => 'https://columna.org.md/biblioteca/repere/12_repere_metodol._biologie_ro_2022-2023_final.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional la informatică în anul de studii 2022-2023', 'url' => 'https://columna.org.md/biblioteca/repere/repere_metodologice_informatica_2022-2023_f.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional la fizică în anul de studii 2022-2023', 'url' => 'https://columna.org.md/biblioteca/repere/fizica_ro_repere_metodologice_2022-2023_final.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional la educație pentru societate în anul de studii 2022-2023', 'url' => 'https://columna.org.md/biblioteca/repere/educatie_pentru_societate_repere_metodologice_2022-2023_ro_1.pdf'],
                    ['title' => 'Repere metodologice de organizare a procesului educațional la educație fizică în anul de studii 2022-2023', 'url' => 'https://columna.org.md/biblioteca/repere/23_educatie_fizica_2022-2023_final.pdf'],
                ],
            ],
            [
                'title' => 'Curriculum naţional (2010)',
                'books' => [
                    ['title' => 'Matematică , curriculumul pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum/maths_l.pdf'],
                    ['title' => 'Biologie , curriculumul pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum/biologie_l.pdf'],
                    ['title' => 'Chimie , curriculumul pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum/chimie_l.pdf'],
                    ['title' => 'Limba şi literatura română , curriculumul pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum/romana_l.pdf'],
                    ['title' => 'Istorie , curriculumul pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum/istorie_l.pdf'],
                    ['title' => 'Geografie , curriculumul pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum/geografie_l.pdf'],
                    ['title' => 'Fizică , curriculumul pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum/fizica_l.pdf'],
                    ['title' => 'Educaţie fizică , curriculumul pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum/ed_fiz_l.pdf'],
                    ['title' => 'Educaţie civică , curriculumul pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum/civica_l.pdf'],
                    ['title' => 'Literatura universală , curriculumul pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum/universala.pdf'],
                    ['title' => 'Matematică , curriculumul pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum/maths_g.pdf'],
                    ['title' => 'Informatică , curriculumul pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum/inform_g.pdf'],
                    ['title' => 'Biologie , curriculumul pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum/biologie_g.pdf'],
                    ['title' => 'Chimie , curriculumul pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum/chimie_g.pdf'],
                    ['title' => 'Limba şi literatura română , curriculumul pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum/romana_g.pdf'],
                    ['title' => 'Limba rusă , curriculumul pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum/rusa.pdf'],
                    ['title' => 'Fizică , curriculumul pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum/fizica_g.pdf'],
                    ['title' => 'Istorie , curriculumul pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum/istorie_g.pdf'],
                    ['title' => 'Geografie , curriculumul pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum/geografie_g.pdf'],
                    ['title' => 'Limba străină , curriculumul pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum/straina_g.pdf'],
                    ['title' => 'Ştiinţe , curriculumul pentru clasa a V-a', 'url' => 'https://columna.org.md/biblioteca/curriculum/stiinte_5.pdf'],
                    ['title' => 'Educaţie plastică , curriculumul pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum/plastica.pdf'],
                    ['title' => 'Educaţie fizică , curriculumul pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum/ed_fiz_g.pdf'],
                    ['title' => 'Educaţie civică , curriculumul pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum/civica_g.pdf'],
                    ['title' => 'Educaţia tehnologică , curriculumul pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum/ed_tehno_g.pdf'],
                    ['title' => 'Dezvoltare personală , curriculumul pentru gimnaziu', 'url' => 'https://columna.org.md/biblioteca/curriculum/cr_dezv_pers_gimn.pdf'],
                    ['title' => 'Dezvoltare personală , curriculumul pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum/cr_dezv_pers.pdf'],
                    ['title' => 'Informatică , curriculumul pentru liceu', 'url' => 'https://columna.org.md/biblioteca/curriculum/inform_l.pdf'],
                ],
            ],
        ];
    }
}
