<?php

namespace App\Support;

/**
 * Orarele migrate din columna.org.md (tabele). Generat automat.
 */
final class OrareSchedules
{
    /**
     * @return array<string, list<array{label: string, headers: list<string>, rows: list<list<string>>}>>
     */
    public static function all(): array
    {
        return [
            'orarul-lectiilor' => [
                [
                    'label' => 'Clasa I C',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.00 – 08.30', 'Dezvoltare personală', 'Educație plastică', 'Matematică', 'Educație tehnologică', 'Educația moral-spirituală'],
                        ['Lecția 2 09.05 – 09.50', 'Matematică', 'Matematică', 'Limba română', 'Educație digitală , gr. 1, Căruntu N. Limba engleză , gr.2, Pascaru M.', 'Educație fizică , gr.1, Dumitrașcu A. Limba engleză , gr.2, Pascaru M.'],
                        ['Lecția 3 10.10 – 10.55', 'Limba română', 'Limba română', 'Matematică', 'Matematică', 'Limba engleză , gr.1, Buga A. Educație fizică , gr.2, Dumitrașcu A.'],
                        ['Lecția 4 11.15 – 12.00', 'Limba română', 'Limba română', 'Educaţie moral-spirituală', 'Limba română', 'Educaţie plastică'],
                        ['Lecția 5 12.20 – 13.05', 'În împărăția lui MATE', 'Limba engleză , gr.1, Buga A. Educație fizică , gr.2, Dumitrașcu A.', 'Educație muzicală', 'Limba română', 'Managementul clasei'],
                        ['13.05 – 14.05', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri'],
                        ['14.05 – 14.50', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1'],
                        ['15.00 – 15.45', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2'],
                    ],
                ],
                [
                    'label' => 'Clasa I I',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.00 – 08.30', 'Dezvoltare personală', 'Limba română', 'Matematică', 'Educaţie muzicală , Ungureanu V.', 'Limba engleză , gr.1, Pascaru M. Educație fizică , gr.2, Dumitrașcu A.'],
                        ['Lecția 2 09.05 – 09.50', 'Limba română', 'Limba română', 'Limba engleză , gr.1, Pascaru M. Educație digitală , gr.2, Căruntu N.', 'Limba română', 'Tainele comunicării'],
                        ['Lecția 3 10.10 – 10.55', 'Matematică', 'Educație fizică , gr.1, Dumitrașcu A. Limba engleză , gr.2, Buga A.', 'Educație digitală , gr.1, Căruntu N. Limba engleză , gr.2, Buga A.', 'Limba română', 'Educaţie plastică'],
                        ['Lecția 4 11.15 – 12.00', 'În împărăția lui MATE', 'Limba engleză , gr.1, Pascaru M. Educație fizică , gr.2, Dumitrașcu A.', 'Limba română', 'Matematică', 'Managementul clasei'],
                        ['Lecția 5 12.20 – 13.05', 'Dezvoltare personală', 'Matematică', 'Matematică', 'Educație moral-spirituală', 'Educație fizică , gr.1, Dumitrașcu A. Limba engleză , gr.2, Buga A.'],
                        ['13.05 – 14.05', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri'],
                        ['14.05 – 14.50', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1'],
                        ['15.00 – 15.45', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2'],
                    ],
                ],
                [
                    'label' => 'Clasa II L',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.00 – 08.45', 'Limba română', 'Limba română', 'Limba română', 'Limba română', 'În împărăția lui MATE'],
                        ['Lecția 2 09.15 – 09.50', 'Limba engleză , gr.1, Pascaru M. Limba engleză , gr.2, Popa N.', 'Educația muzicală , Ungureanu V.', 'Limba română', 'Matematică', 'Științe'],
                        ['Lecția 3 10.10 – 10.55', 'Limba română', 'Limba română', 'Matematică', 'Educaţie fizică , Ciobanu A.', 'Managementul clasei'],
                        ['Lecția 4 11.15 – 12.00', 'Matematică', 'Matematică', 'Limba engleză , gr.1, Pascaru M. Educaţie digitală , gr.2, Căruntu N.', 'Dezvoltare personală', 'Educaţie plastică'],
                        ['Lecția 5 12.35 – 13.20', 'Educaţie fizică , Ciobanu A.', 'Educaţie moral-spirituală', 'Educaţie digitală , gr.1, Căruntu N. Limba engleză , gr.2, Popa N.', 'Tainele comunicării', 'Limba engleză , gr.1, Pascaru M. Limba engleză , gr.2, Popa N.'],
                        ['13.20 – 14.05', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri'],
                        ['14.05 – 14.50', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1'],
                        ['15.00 – 15.45', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2'],
                    ],
                ],
                [
                    'label' => 'Clasa II T',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.00 – 08.45', 'Educaţie digitală, gr. 1 Limba engleză, gr. 2', 'Limba română', 'Matematică', 'Limba română', 'Științe'],
                        ['Lecția 2 09.15 – 09.50', 'Limba română', 'Limba română', 'Educaţie fizică , Ciobanu A.', 'Tainele comunicării', 'În împărăția lui MATE'],
                        ['Lecția 3 10.10 – 10.55', 'Educaţie fizică , Ciobanu A.', 'Educaţie muzicală , Ungureanu V.', 'Limba română', 'Matematică', 'Limba engleză , gr.1, Pascaru M. Limba engleză , gr.2, Popa N.'],
                        ['Lecția 4 11.15 – 12.00', 'Limba engleză , gr.1, Pascaru M. Limba engleză , gr.2, Popa N.', 'Matematică', 'Limba română', 'Limba engleză , gr.1, Pascaru M. Educaţie digitală , gr.2, Căruntu N.', 'Educaţie plastică'],
                        ['Lecția 5 12.35 – 13.20', 'Limba română', 'Educaţie moral-spirituală', 'Dezvoltare personală', 'Educaţie digitală , gr.1, Căruntu N. Limba engleză , gr.2, Popa N.', 'Managementul clasei', ''],
                        ['13.20 – 14.05', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri'],
                        ['14.05 – 14.50', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1'],
                        ['15.00 – 15.45', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2'],
                    ],
                ],
                [
                    'label' => 'Clasa III C',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.00 – 08.45', 'Limba română', 'Limba română', 'Matematică', 'Limba română', 'Științe'],
                        ['Lecția 2 08.55 – 09.35', 'Limba română', 'Limba română', 'Educaţie muzicală , Ungureanu V.', 'Matematică', 'Educaţie fizică , Ciobanu A.'],
                        ['Lecția 3 10.10 – 10.55', 'Limba engleză , gr.1, Popa N. Limba engleză , gr.2, Pascaru M.', 'Limba engleză , gr.1, Popa N. Limba engleză , gr.2, Pascaru M.', 'Limba română', 'Limba engleză , gr.1, Popa N. Limba engleză , gr.2, Pascaru M.', 'Educaţie tehnologică'],
                        ['Lecția 4 11.15 – 12.00', 'Matematică', 'Matematică', 'Limba română', 'Tainele comunicării', 'Educaţie plastică'],
                        ['12.00 – 12.45', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri'],
                        ['Lecția 5 12.45 – 13.30', 'Educaţie moral-spirituală', 'Educaţie fizică , Ciobanu A.', 'În împărăția lui MATE', 'Managementul clasei', 'Dezvoltare personală'],
                        ['14.00 – 14.45', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1'],
                        ['15.00 – 15.45', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2'],
                    ],
                ],
                [
                    'label' => 'Clasa III L',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.00 – 08.45', 'Educaţie fizică , Ciobanu A.', 'Matematică', 'Limba română', 'Limba română', 'Tainele comunicării'],
                        ['Lecția 2 08.55 – 09.35', 'Matematică', 'Limba română', 'Limba română', 'Limba română', 'Limba engleză , gr.1, Buga A. Limba engleză , gr.2, Popa N.'],
                        ['Lecția 3 10.10 – 10.55', 'Limba română', 'Limba română', 'Matematică', 'Științe', 'În împărăția lui MATE'],
                        ['Lecția 4 11.15 – 12.00', 'Limba română', 'Limba engleză , gr.1, Buga A. Limba engleză , gr.2, Popa N.', 'Limba engleză , gr.1, Buga A. Limba engleză , gr.2, Popa N.', 'Educaţie fizică , Ciobanu A.', 'Educaţie tehnologică'],
                        ['12.00 – 12.45', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri'],
                        ['Lecția 5 12.45 – 13.30', 'Educaţie moral-spirituală', 'Educaţie muzicală', 'Dezvoltare personală', 'Managementul clasei', 'Educaţie plastică'],
                        ['14.00 – 14.45', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1'],
                        ['15.00 – 15.45', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2'],
                    ],
                ],
                [
                    'label' => 'Clasa IV L',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.00 – 08.45', 'Limba română', 'Educaţie fizică , Ciobanu A.', 'Limba română', 'Matematică', 'Tainele comunicării'],
                        ['Lecția 2 08.55 – 09.35', 'Limba română', 'Matematică', 'Limba română', 'Limba română', 'În împărăția lui MATE'],
                        ['Lecția 3 10.10 – 10.55', 'Limba engleză , gr.1, Cociug S. Limba engleză , gr.2, Pascaru M.', 'Limba engleză , gr.1, Cociug S. Limba engleză , gr.2, Pascaru M.', 'Educaţie muzicală , Ungureanu V.', 'Limba engleză , gr.1, Cociug S. Limba engleză , gr.2, Pascaru M.', 'Educaţie plastică'],
                        ['Lecția 4 11.15 – 12.00', 'Matematică', 'Limba română', 'Matematică', 'Științe', 'Educaţie fizică , Ciobanu A.'],
                        ['12.00 – 12.45', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri'],
                        ['Lecția 5 12.45 – 13.30', 'Educaţie moral-spirituală', 'Limba română', 'Dezvoltare personală', 'Managementul clasei', 'Educaţie tehnologică'],
                        ['14.00 – 14.45', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1'],
                        ['15.00 – 15.45', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2'],
                    ],
                ],
                [
                    'label' => 'Clasa IV N',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.00 – 08.45', 'Matematică', 'Limba engleză , gr.1, Popa N. Limba engleză , gr.2, Buga A.', 'Educaţie muzicală , Ungureanu V.', 'Limba română', 'Matematică'],
                        ['Lecția 2 09.05 – 09.50', 'Istoria românilor și universală', 'Matematică', 'Matematică', 'Educaţie fizică , Dumitrașcu A.', 'Educaţie plastică , Nasoila L.'],
                        ['Lecția 3 10.30 – 11.15', 'Educaţie fizică , Dumitrașcu A.', 'Limba română', 'Limba română', 'Științe', 'Dezvoltare personală'],
                        ['Lecția 4 11.30 – 12.15', 'Limba română', 'Limba română', 'Limba română', 'Limba engleză , gr.1, Popa N. Limba engleză , gr.2, Buga A.', 'Limba engleză , gr.1, Popa N. Limba engleză , gr.2, Buga A.'],
                        ['12.15 – 13.00', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri'],
                        ['Lecția 5 13.00 – 13.45', 'Limba română', 'În împărăția lui MATE', 'Tainele comunicării', 'Educaţie moral-spirituală', 'Educaţie tehnologică'],
                        ['14.15 – 15.00', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1'],
                        ['15.05 – 15.45', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2'],
                    ],
                ],
                [
                    'label' => 'Clasa IV S',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.00 – 08.45', 'Limba engleză , gr.1, Popa N. Limba engleză , gr.2, Buga A.', 'Limba română', 'Limba română', 'Limba română', 'Limba engleză , gr.1, Popa N. Limba engleză , gr.2, Buga A.'],
                        ['Lecția 2 09.05 – 09.50', 'Educaţie fizică , Ciobanu A.', 'Limba engleză , gr.1, Popa N. Limba engleză , gr.2, Buga A.', 'Limba română', 'Educaţie muzicală , Ungureanu V.', 'Limba română'],
                        ['Lecția 3 10.30 – 11.15', 'Limba română', 'Limba română', 'Matematică', 'Matematică', 'Matematică'],
                        ['Lecția 4 11.30 – 12.15', 'Istoria românilor și universală', 'Matematică', 'Educaţie fizică , Ciobanu A.', 'Științe', 'În împărăția lui MATE'],
                        ['12.15 – 13.00', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri', 'Plimbări, jocuri'],
                        ['Lecția 5 13.00 – 13.45', 'Educaţie moral-spirituală', 'Dezvoltare personală', 'Tainele comunicării', 'Educaţie plastică', 'Educaţie tehnologică'],
                        ['14.15 – 15.00', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1', 'PTA 1'],
                        ['15.05 – 15.45', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2', 'PTA 2'],
                    ],
                ],
                [
                    'label' => 'Clasa V 1',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.15 – 09.00', 'Limba și literatura română , Russu I. (s. 29)', 'Matematică , Cociurca N. (s. 36)', 'Educaţie fizică , Ciobanu A.', 'Științe , Barbacaru A. (s. 27)', 'Matematică , Cociurca N. (s. 36)'],
                        ['Lecția 2 09.10 – 09.55', 'Limba și literatura română , Russu I. (s. 29)', 'Limba și literatura română , Russu I. (s. 29)', 'Limba engleză , gr.1, Buga A. (s. 6) Informatică , gr.2, Iurco O. (s. 24)', 'Limba și literatura română , Russu I. (s. 23)', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)'],
                        ['Lecția 3 10.10 – 10.55', 'Matematică , Cociurca N. (s. 36)', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Informatică , gr.1, Iurco O. (s. 24) Limba engleză , gr.2, Pascaru M. (s. 14)', 'Geografie , Cartaleanu E. (s. 22)', 'Limba și literatura română , Russu I. (s. 30)'],
                        ['Lecția 4 11.10 – 11.55', 'Istoria românilor și universală , Cîrlig E. (s. 29)', 'Educaţie fizică , Ciobanu A.', 'Educaţie muzicală , Ungureanu V. (s. 26)', 'Geografie aplicată , Cartaleanu E. (s. 22)', 'Educaţie plastică , Bardița I. (s. 36)'],
                        ['Lecția 5 12.10 – 12.55', 'Limba engleză , gr.1, Buga A. (s. 6) Limba engleză , gr.2, Pascaru M. (s. 14)', 'Educație tehnologică , gr.1, Barbacaru A. (s. 27) Robotică , gr.2, Voitcovschi D. (s. 24) / Robotică , gr.1, Voitcovschi D. (s. 24) Educație tehnologică , gr.2, Barbacaru A. (s. 27)', 'Istoria românilor și universală , Cîrlig E. (s. 29)', 'Limba și literatura română , Russu I. (s. 23)', 'Dezvoltare personală , Arhip S. (s. 27)'],
                        ['Lecția 6 13.25 – 14.10', 'Educaţie pentru societate , Cîrlig E. (s. 29)', 'Limba rusă , gr.0, Foghelizang Iu. (s. 23)', 'Matematică , Cociurca N. (s. 36)', 'Limba rusă , gr.1, Foghelizang Iu. (s. 23)', 'Limba engleză , gr.1, Buga A. (s. 6) Limba engleză , gr.2, Pascaru M. (s. 14)'],
                        ['Lecția 7 14.15 – 15.00', 'Limba rusă , gr.1, Foghelizang Iu. (s. 26)', 'Consultații Geografie , Cartaleanu E. (s. 22)', 'Limba rusă , gr.0, Foghelizang Iu. (s. 26)', '', 'Consultații Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32) Limba rusă , Foghelizang Iu. (s. 26) Matematică , Cociurca N. (s. 36)'],
                        ['Lecția 8 15.10 – 15.55', '', '', '', '', ''],
                    ],
                ],
                [
                    'label' => 'Clasa V 2',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.15 – 09.00', 'Științe , Barbacaru A. (s. 27)', 'Limba și literatura română , Russu I. (s. 29)', 'Istoria românilor și universală , Cîrlig E. (s. 29)', 'Matematică , Cociurca N. (s. 36)', 'Limba și literatura română , Russu I. (s. 29)'],
                        ['Lecția 2 09.10 – 09.55', 'Matematică , Cociurca N. (s. 36)', 'Matematică , Cociurca N. (s. 36)', 'Geografie , Cartaleanu E. (s. 22)', 'Limba engleză , gr.1, Popa N. (s. 4) Limba engleză , gr.2, Cociug S. (s. 21)', 'Limba și literatura română , Russu I. (s. 29)'],
                        ['Lecția 3 10.10 – 10.55', 'Istoria românilor și universală , Cîrlig E. (s. 29)', 'Educaţie fizică , Ciobanu A.', 'Geografie aplicată , Cartaleanu E. (s. 22)', 'Educaţie muzicală , Ungureanu V. (s. 26)', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)'],
                        ['Lecția 4 11.10 – 11.55', 'Limba și literatura română , Russu I. (s. 23)', 'Educație tehnologică , gr.1, Barbacaru A. (s. 27) Robotică , gr.2, Voitcovschi D. (s. 24) / Robotică , gr.1, Voitcovschi D. (s. 24) Educație tehnologică , gr.2, Barbacaru A. (s. 27)', 'Educaţie pentru societate , Cîrlig E. (s. 29)', 'Limba și literatura română , Russu I. (s. 23)', 'Matematică , Cociurca N. (s. 23)'],
                        ['Lecția 5 12.10 – 12.55', 'Limba engleză , gr.1, Popa N. (s. 4) Limba engleză , gr.2, Cociug S. (s. 21)', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Informatică , gr.1, Iurco O. (s. 24) Limba engleză , gr.2, Cociug S. (s. 21)', 'Educaţie fizică , Ciobanu A.', 'Educaţie plastică , Bardița I. (s. 36)'],
                        ['Lecția 6 13.25 – 14.10', 'Limba și literatura română , Russu I. (s. 22)', 'Limba rusă , gr.0, Foghelizang Iu. (s. 23)', 'Limba engleză , gr.1, Popa N. (s. 4) Informatică , gr.2, Iurco O. (s. 24)', 'Limba rusă , gr.1, Foghelizang Iu. (s. 23)', 'Dezvoltare personală , Foghelizang Iu. (s. 26'],
                        ['Lecția 7 14.15 – 15.00', 'Limba rusă , gr.1, Foghelizang Iu. (s. 26)', 'Consultații Geografie , Cartaleanu E. (s. 22)', 'Limba rusă , gr.0, Foghelizang Iu. (s. 26)', '', 'Consultații Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32) Limba rusă , Foghelizang Iu. (s. 26) Matematică , Cociurca N. (s. 36)'],
                        ['Lecția 8 15.10 – 15.55', '', '', '', '', ''],
                    ],
                ],
                [
                    'label' => 'Clasa VI 1',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.15 – 09.00', 'Istoria românilor și universală , Cîrlig E. (s. 19)', 'Fizică , Solomonenco V. (s. 33)', 'Dezvoltare personală , Barbacaru A. (s. 27)', 'Educaţie fizică , Ciobanu A.', 'Educaţie fizică , Ciobanu A.'],
                        ['Lecția 2 09.10 – 09.55', 'Limba și literatura română , Iacubovschi M. (s. 30)', 'Limba și literatura română , Iacubovschi M. (s. 30)', 'Istoria românilor și universală , Cîrlig E. (s. 19)', 'Biologie , Barbacaru A. (s. 27)', 'Geografie , Cartaleanu E. (s. 22)'],
                        ['Lecția 3 10.10 – 10.55', 'Matematică , Căruntu N. (s. 23)', 'Matematică , Căruntu N. (s. 29)', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Limba și literatura română , Iacubovschi M. (s. 30)', 'Matematică , Căruntu N. (s. 19)'],
                        ['Lecția 4 11.10 – 11.55', 'Limba engleză , gr.1, Buga A. (s. 6) Informatică , gr.2, Iurco O. (s. 24)', 'Matematică , Căruntu N. (s. 29)', 'Limba și literatura română , Iacubovschi M. (s. 30)', 'Limba rusă , Foghelizang Iu. (s. 30)', 'Limba rusă , Foghelizang Iu. (s. 26)'],
                        ['Lecția 5 12.10 – 12.55', 'Educaţie pentru societate , Cîrlig E. (s. 29)', 'Educaţie plastică , Bardița I. (s. 36)', 'Limba engleză , gr.1, Buga A. (s. 6) Limba engleză , gr.2, Pascaru M. (s. 14)', 'Limba engleză , gr.1, Buga A. (s. 6) Limba engleză , gr.2, Pascaru M. (s. 14)', 'Limba și literatura română , Iacubovschi M. (s. 20)'],
                        ['Lecția 6 13.25 – 14.10', 'Limba și literatura română , Iacubovschi M. (s. 30)', 'Educaţie muzicală , Ungureanu V. (s. 26)', 'Educație tehnologică , gr.1, Barbacaru A. (s. 27) Robotică , gr.2, Voitcovschi D. (s. 24) / Robotică , gr.1, Voitcovschi D. (s. 24) Educație tehnologică , gr.2, Barbacaru A. (s. 27)', 'Informatică , gr.1, Iurco O. (s. 24) Limba engleză , gr.2, Pascaru M. (s. 14)', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)'],
                        ['Lecția 7 14.15 – 15.00', 'Consultații Matematică , Damian Iu. (s. 20)', 'Consultații Geografie , Cartaleanu E. (s. 22)', '', '', 'Consultații Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32) Limba rusă , Foghelizang Iu. (s. 26)'],
                        ['Lecția 8 15.10 – 15.55', '', '', '', '', ''],
                    ],
                ],
                [
                    'label' => 'Clasa VI 2',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.15 – 09.00', 'Matematică , Căruntu N. (s. 23)', 'Limba și literatura română , Iacubovschi M. (s. 30)', 'Limba și literatura română , Iacubovschi M. (s. 30)', 'Limba și literatura română , Iacubovschi M. (s. 30)', 'Limba și literatura română , Iacubovschi M. (s. 30)'],
                        ['Lecția 2 09.10 – 09.55', 'Istoria românilor și universală , Cîrlig E. (s. 19)', 'Educaţie fizică , Ciobanu A.', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Geografie , Cartaleanu E. (s. 22)', 'Limba rusă , Foghelizang Iu. (s. 26)'],
                        ['Lecția 3 10.10 – 10.55', 'Biologie , Barbacaru A. (s. 27)', 'Dezvoltare personală , Moșu A. (s. 23)', 'Istoria românilor și universală , Cîrlig E. (s. 29)', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Educaţie fizică , Ciobanu A.'],
                        ['Lecția 4 11.10 – 11.55', 'Limba engleză , gr.1, Moșu A. (s. 4) Informatică , gr.2, Iurco O. (s. 24)', 'Fizică , Solomonenco V. (s. 33)', 'Educație tehnologică , gr.1, Barbacaru A. (s. 27) Robotică , gr.2, Voitcovschi D. (s. 24) / Robotică , gr.1, Voitcovschi D. (s. 24) Educație tehnologică , gr.2, Barbacaru A. (s. 27)', 'Educaţie muzicală , Ungureanu V. (s. 26)', 'Limba și literatura română , Iacubovschi M. (s. 30)'],
                        ['Lecția 5 12.10 – 12.55', 'Limba și literatura română , Iacubovschi M. (s. 30)', 'Matematică , Căruntu N. (s. 29)', 'Limba engleză , gr.1, Moșu A. (s. 26) Limba engleză , gr.2, Pascaru M. (s. 14)', 'Informatică , gr.1, Iurco O. (s. 24) Limba engleză , gr.2, Pascaru M. (s. 14)', 'Matematică , Căruntu N. (s. 23)'],
                        ['Lecția 6 13.25 – 14.10', 'Limba rusă , Foghelizang Iu. (s. 26)', 'Educaţie plastică , Bardița I. (s. 36)', 'Educaţie moral-spirituală , Cîrlig E. (s. 19)', 'Limba engleză , gr.1, Moșu A. (s. 23) Limba engleză , gr.2, Pascaru M. (s. 14)', 'Matematică , Căruntu N. (s. 23)'],
                        ['Lecția 7 14.15 – 15.00', 'Consultații Matematică , Damian Iu. (s. 20)', 'Consultații Geografie , Cartaleanu E. (s. 22)', '', '', 'Consultații Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32) Limba rusă , Foghelizang Iu. (s. 26)'],
                        ['Lecția 8 15.10 – 15.55', '', '', '', '', ''],
                    ],
                ],
                [
                    'label' => 'Clasa VII 1',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.15 – 09.00', 'Geografie Cartaleanu E. (s. 22)', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Matematică Damian Iu. (s. 20)', 'Fizică Solomonenco V. (s. 33)', 'Matematică Damian Iu. (s. 20)'],
                        ['Lecția 2 09.10 – 09.55', 'Matematică Damian Iu. (s. 20)', 'Limba engleză , gr.1, Pascaru M. (s. 14) Limba engleză , gr.2, Cociug S. (s. 21)', 'Matematică Damian Iu. (s. 20)', 'Educaţie fizică Ciobanu A.', 'Educaţie pentru societate Demerji S. (s. 19)'],
                        ['Lecția 3 10.10 – 10.55', 'Limba și literatura română Russu I. (s. 19)', 'Biologie Barbacaru A. (s. 27)', 'Limba și literatura română Russu I. (s. 19)', 'Biologie Barbacaru A. (s. 27)', 'Fizică Solomonenco V. (s. 33)'],
                        ['Lecția 4 11.10 – 11.55', 'Limba rusă Foghelizang Iu. (s. 26)', 'Educaţie muzicală Ungureanu V. (s. 19)', 'Informatică , gr.1, Iurco O. (s. 28) Limba engleză , gr.2, Cociug S. (s. 21)', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Limba și literatura română Russu I. (s. 21)'],
                        ['Lecția 5 12.10 – 12.55', 'Istoria românilor și universală Demerji S. (s. 19)', 'Dezvoltare personală Pascaru M. (s. 14)', 'Limba și literatura română Russu I. (s. 19)', 'Chimie Bujor-Cobili C. (s. 34)', 'Limba rusă Foghelizang Iu. (s. 26)'],
                        ['Lecția 6 13.25 – 14.10', 'Limba engleză , gr.1, Pascaru M. (s. 14) Limba engleză , gr.2, Cociug S. (s. 21)', 'Educație tehnologică , gr.1, Barbacaru A. (s. 27) Robotică , gr.2, Voitcovschi D. (s. 24) / Robotică , gr.1, Voitcovschi D. (s. 24) Educație tehnologică , gr.2, Barbacaru A. (s. 27)', 'Educaţie fizică Ciobanu A.', 'Istoria românilor și universală Demerji S. (s. 29)', 'Educaţie plastică Bardița I. (s. 36)'],
                        ['Lecția 7 14.15 – 15.00', 'Consultații Matematică , Damian Iu. (s. 20)', 'Limba și literatura română Russu I. (s. 19)', 'Informatică , gr.2 Iurco O. (s. 24)', 'Limba engleză , gr.1 Pascaru M. (s. 14)', 'Consultații Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32) Limba rusă , Foghelizang Iu. (s. 26)'],
                    ],
                ],
                [
                    'label' => 'Clasa VII 2',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.15 – 09.00', 'Matematică Damian Iu. (s. 20)', 'Matematică Damian Iu. (s. 20)', 'Limba și literatura română Russu I. (s. 19)', 'Chimie Bujor-Cobili C. (s. 34)', 'Fizică Solomonenco V. (s. 33)'],
                        ['Lecția 2 09.10 – 09.55', 'Biologie Barbacaru A. (s. 27)', 'Limba engleză , gr.1, Moșu A. (s. 23) Limba engleză , gr.2, Cociug S. (s. 21)', 'Limba și literatura română Russu I. (s. 19)', 'Fizică Solomonenco V. (s. 33)', 'Matematică Damian Iu. (s. 20)'],
                        ['Lecția 3 10.10 – 10.55', 'Geografie Cartaleanu E. (s. 22)', 'Limba și literatura română Russu I. (s. 19)', 'Educaţie fizică Ciobanu A.', 'Limba rusă Foghelizang Iu. (s. 20)', 'Matematică Damian Iu. (s. 20)'],
                        ['Lecția 4 11.10 – 11.55', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Educaţie plastică , Bardița I. (s. 36)', 'Limba engleză , gr.1, Moșu A. (s. 6) Limba engleză , gr.2, Cociug S. (s. 21)', 'Istoria românilor și universală Demerji S. (s. 19)', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)'],
                        ['Lecția 5 12.10 – 12.55', 'Limba rusă Foghelizang Iu. (s. 26)', 'Limba și literatura română Russu I. (s. 19)', 'Educație tehnologică , gr.1, Barbacaru A. (s. 27) Robotică , gr.2, Voitcovschi D. (s. 24) / Robotică , gr.1, Voitcovschi D. (s. 24) Educație tehnologică , gr.2, Barbacaru A. (s. 27)', 'Biologie Barbacaru A. (s. 27)', 'Educaţie fizică Ciobanu A.'],
                        ['Lecția 6 13.25 – 14.10', 'Limba engleză , gr.1, Moșu A. (s. 19) Limba engleză , gr.2, Cociug S. (s. 21)', '', 'Educaţie muzicală Ungureanu V. (s. 26)', 'Limba și literatura română Russu I. (s. 19)', 'Istoria românilor și universală Demerji S. (s. 19)'],
                        ['Lecția 7 14.15 – 15.00', 'Consultații Matematică , Damian Iu. (s. 20)', 'Consultații Geografie , Cartaleanu E. (s. 22)', 'Informatică , gr.2 Iurco O. (s. 24)', 'Informatică , gr.1 Iurco O. (s. 24)', 'Dezvoltare personală / Educaţie pentru societate Russu I. (s. 23)'],
                    ],
                ],
                [
                    'label' => 'Clasa VIII 1',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.15 – 09.00', 'Limba și literatura română Iacubovschi M. (s. 30)', 'Educaţie muzicală Ungureanu V. (s. 26)', 'Limba engleză , gr.1, Pascaru M. (s. 14) Informatică , gr.2, Iurco O. (s. 24)', 'Educaţie fizică Dumitrașcu A.', 'Chimie Bujor-Cobili C. (s. 34)'],
                        ['Lecția 2 09.10 – 09.55', 'Geografie Cartaleanu E. (s. 22)', 'Chimie Bujor-Cobili C. (s. 34)', 'Istoria românilor și universală Demerji S. (s. 26)', 'Limba rusă Foghelizang Iu. (s. 19)', 'Limba și literatura română Iacubovschi M. (s. 21)'],
                        ['Lecția 3 10.10 – 10.55', 'Informatică , gr.1, Iurco O. (s. 24) Limba engleză , gr.2, Moșu A. (s. 4)', 'Limba și literatura română Iacubovschi M. (s. 30)', 'Limba rusă Foghelizang Iu. (s. 33)', 'Matematică Cociurca N. (s. 36)', 'Educație tehnologică , gr.1, Barbacaru A. (s. 27) Tehnologii informaționale , gr.2, Iurco O. (s. 24) / Tehnologii informaționale , gr.1, Iurco O. (s. 24) Educație tehnologică , gr.2, Barbacaru A. (s. 27)'],
                        ['Lecția 4 11.10 – 11.55', 'Biologie Barbacaru A. (s. 27)', 'Matematică Cociurca N. (s. 36)', 'Matematică Cociurca N. (s. 36)', 'Limba și literatura română Iacubovschi M. (s. 6)', 'Biologie Barbacaru A. (s. 27)'],
                        ['Lecția 5 12.10 – 12.55', 'Matematică Cociurca N. (s. 36)', 'Fizică Solomonenco V. (s. 33)', 'Limba și literatura română Iacubovschi M. (s. 30)', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Fizică Solomonenco V. (s. 33)'],
                        ['Lecția 6 13.25 – 14.10', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Limba engleză , gr.1, Pascaru M. (s. 14) Limba engleză , gr.2, Moșu A. (s. 21)', 'Educaţie pentru societate Golban O. (s. 32)', 'Dezvoltare personală Golban O. (s. 27)', 'Educaţie fizică Dumitrașcu A.'],
                        ['Lecția 7 14.15 – 15.00', 'Limba engleză , gr.1, Pascaru M. (s. 14) Limba engleză , gr.2, Moșu A. (s. 21)', 'Consultații Geografie , Cartaleanu E. (s. 22)', '', 'Istoria românilor și universală Demerji S. (s. 29)', 'Consultații Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32) Limba rusă , Foghelizang Iu. (s. 26)'],
                        ['Lecția 8 15.10 – 15.55', 'Consultații Matematică Damian Iu. (s. 20)', '', '', '', ''],
                    ],
                ],
                [
                    'label' => 'Clasa VIII 2',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.15 – 09.00', 'Matematică Cociurca N. (s. 36)', 'Chimie Bujor-Cobili C. (s. 34)', 'Limba engleză , gr.1, Buga A. (s. 6) Informatică , gr.2, Iurco O. (s. 24)', 'Istoria românilor și universală Demerji S. (s. 29)', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)'],
                        ['Lecția 2 09.10 – 09.55', 'Dezvoltare personală Buga A. (s. 23)', 'Fizică Solomonenco V. (s. 33)', 'Biologie Barbacaru A. (s. 27)', 'Educaţie pentru societate Buga A. (s. 26)', 'Biologie Barbacaru A. (s. 27)'],
                        ['Lecția 3 10.10 – 10.55', 'Limba engleză , gr.1, Buga A. (s. 6) Limba engleză , gr.2, Moșu A. (s. 4)', 'Matematică Cociurca N. (s. 36)', 'Limba și literatura română Iacubovschi M. (s. 30)', 'Educaţie fizică Dumitrașcu A.', 'Chimie Bujor-Cobili C. (s. 34)'],
                        ['Lecția 4 11.10 – 11.55', 'Geografie Cartaleanu E. (s. 22)', 'Limba și literatura română Iacubovschi M. (s. 30)', 'Limba rusă Foghelizang Iu. (s. 22)', 'Matematică Cociurca N. (s. 36)', 'Educaţie fizică Dumitrașcu A.'],
                        ['Lecția 5 12.10 – 12.55', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Educaţie muzicală Ungureanu V. (s. 26)', 'Matematică Cociurca N. (s. 36)', 'Limba rusă Foghelizang Iu. (s. 26)', 'Istoria românilor și universală Demerji S. (s. 29)'],
                        ['Lecția 6 13.25 – 14.10', 'Educație tehnologică , gr.1, Barbacaru A. (s. 27) Tehnologii informaționale , gr.2, Iurco O. (s. 24) / Tehnologii informaționale , gr.1, Iurco O. (s. 24) Educație tehnologică , gr.2, Barbacaru A. (s. 27)', 'Limba engleză , gr.1, Buga A. (s. 6) Limba engleză , gr.2, Moșu A. (s. 21)', 'Limba și literatura română Iacubovschi M. (s. 30)', 'Limba și literatura română Iacubovschi M. (s. 30)', 'Limba și literatura română Iacubovschi M. (s. 30)'],
                        ['Lecția 7 14.15 – 15.00', 'Informatică , gr.1, Iurco O. (s. 24) Limba engleză , gr.2, Moșu A. (s. 21)', 'Consultații Geografie , Cartaleanu E. (s. 22)', 'Fizică Solomonenco V. (s. 33)', '', 'Consultații Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32) Limba rusă , Foghelizang Iu. (s. 26)'],
                        ['Lecția 8 15.10 – 15.55', 'Consultații Matematică Damian Iu. (s. 20)', '', '', '', ''],
                    ],
                ],
                [
                    'label' => 'Clasa IX 1',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.15 – 09.00', 'Educaţie fizică Dumitrașcu A.', 'Biologie Barbacaru A. (s. 27)', 'Matematică Cociurca N. (s. 36)', 'Informatică , gr.1, Iurco. (s. 24) Limba engleză , gr.2, Popa N. (s. 4)', 'Istoria românilor și universală Demerji S. (s. 29)'],
                        ['Lecția 2 09.10 – 09.55', 'Limba rusă Foghelizang Iu. (s. 26)', 'Geografie Cartaleanu E. (s. 22)', 'Limba engleză , gr.1, Moșu A. (s. 23) Limba engleză , gr.2, Popa N. (s. 4)', 'Limba engleză , gr.1, Moșu A. (s. 6) Informatică , gr.2, Iurco. (s. 24)', 'Matematică Cociurca N. (s. 36)'],
                        ['Lecția 3 10.10 – 10.55', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Chimie Bujor-Cobili C. (s. 34)', 'Biologie Barbacaru A. (s. 27)', 'Limba și literatura română Russu I. (s. 23)', 'Limba rusă Foghelizang Iu. (s. 26)'],
                        ['Lecția 4 11.10 – 11.55', 'Matematică Cociurca N. (s. 36)', 'Limba și literatura română Russu I. (s. 23)', 'Istoria românilor și universală Demerji S. (s. 33)', 'Chimie Bujor-Cobili C. (s. 34)', 'Fizică Solomonenco V. (s. 33)'],
                        ['Lecția 5 12.10 – 12.55', 'Educație tehnologică , gr.1, Barbacaru A. (s. 27) Tehnologii informaționale , gr.2, Iurco O. (s. 24) / Tehnologii informaționale , gr.1, Iurco O. (s. 24) Educație tehnologică , gr.2, Barbacaru A. (s. 27)', 'Limba engleză , gr.1, Moșu A. (s. 23) Limba engleză , gr.2, Popa N. (s. 6)', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Fizică Solomonenco V. (s. 33)', 'Matematică Cociurca N. (s. 34)'],
                        ['Lecția 6 13.25 – 14.10', 'Educaţie pentru societate Demerji S. (s. 34)', 'Limba și literatura română Russu I. (s. 29)', 'Limba și literatura română Russu I. (s. 33)', 'Educaţie fizică Dumitrașcu A.', 'Dezvoltare personală Cociurca N. (s. 22)'],
                        ['Lecția 7 14.15 – 15.00', 'Limba și literatura română Russu I. (s. 22)', 'Consultații pentru examen: Istoria românilor și universală Demerji S. (s. 29)', 'Consultații pentru examen: Matematică Cociurca N. (s. 36)', 'Consultații pentru examen: Limba și literatura română Russu I. (s. 26)', ''],
                    ],
                ],
                [
                    'label' => 'Clasa IX 2',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.15 – 09.00', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Geografie Cartaleanu E. (s. 22)', 'Istoria românilor și universală Demerji S. (s. 33)', 'Limba și literatura română Russu I. (s. 23', 'Educație tehnologică , gr.1, Barbacaru A. (s. 27) Tehnologii informaționale , gr.2, Iurco O. (s. 24) / Tehnologii informaționale , gr.1, Iurco O. (s. 24) Educație tehnologică , gr.2, Barbacaru A. (s. 27)'],
                        ['Lecția 2 09.10 – 09.55', 'Educaţie fizică Dumitrașcu A.', 'Biologie Barbacaru A. (s. 27)', 'Matematică Cociurca N. (s. 33)', 'Matematică Cociurca N. (s. 36)', 'Fizică Solomonenco V. (s. 33)'],
                        ['Lecția 3 10.10 – 10.55', 'Limba rusă Foghelizang Iu. (s. 26)', 'Fizică Solomonenco V. (s. 33)', 'Chimie Bujor-Cobili C. (s. 34)', 'Limba engleză , gr.1, Buga A. (s. 6) Informatică , gr.2, Iurco O. (s. 24)', 'Matematică Cociurca N. (s. 36)'],
                        ['Lecția 4 11.10 – 11.55', 'Istoria românilor și universală Demerji S. (s. 30)', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Limba și literatura română Russu I. (s. 23)', 'Biologie Barbacaru A. (s. 27)', 'Chimie Bujor-Cobili C. (s. 34)'],
                        ['Lecția 5 12.10 – 12.55', 'Limba și literatura română Russu I. (s. 22)', 'Matematică Cociurca N. (s. 22)', 'Educaţie pentru societate Demerji S. (s. 33)', 'Educaţie fizică Dumitrașcu A.', 'Limba și literatura română Russu I. (s. 26)'],
                        ['Lecția 6 13.25 – 14.10', 'Limba engleză , gr.1, Buga A. (s. 6) Limba engleză , gr.2, Popa N. (s. 4)', 'Dezvoltare personală Cociurca N. (s. 22)', 'Limba rusă Foghelizang Iu. (s. 22)', 'Limba engleză , gr.1, Buga A. (s. 6) Limba engleză , gr.2, Popa N. (s. 4)', 'Limba și literatura română Russu I. (s. 29)'],
                        ['Lecția 7 14.15 – 15.00', 'Consultații pentru examen: Matematică Cociurca N. (s. 36)', '', 'Consultații pentru examen: Limba și literatura română Russu I. (s. 33)', 'Limba engleză , gr.2, Popa N. (s. 4)', 'Informatică , gr.1, Iurco O. (s. 24)'],
                        ['Lecția 8 15.10 – 15.55', 'Consultații pentru examen: Istoria românilor și universală Demerji S. (s. 29)', '', '', '', ''],
                    ],
                ],
                [
                    'label' => 'Clasa X R',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.15 – 09.00', 'Informatică , gr.1 Iurco O. (s. 24)', '', '', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', ''],
                        ['Lecția 2 09.10 – 09.55', 'Informatică , gr.1 Iurco O. (s. 24)', 'Biologie Dorofeev A. (s. 26)', 'Educaţie fizică Dumitrașcu A.', 'Chimie Bujor-Cobili C. (s. 34)', 'Dezvoltare personală Bujor-Cobili C. (s. 34)'],
                        ['Lecția 3 10.10 – 10.55', 'Limba și literatura română Iacubovschi M. (s. 30)', 'Biologie Dorofeev A. (s. 26)', 'Matematică Damian Iu. (s. 26)', 'Istoria românilor și universală Demerji S. (s. 29)', 'Istoria românilor și universală Demerji S. (s. 29)'],
                        ['Lecția 4 11.10 – 11.55', 'Fizică Solomonenco V. (s. 33)', 'Limba engleză , gr.1, Cociug S. (s. 21) Limba engleză , gr.2, Moșu A. (s. 14)', 'Chimie Bujor-Cobili C. (s. 34)', 'Limba engleză , gr.1, Cociug S. (s. 21) Limba engleză , gr.2, Moșu A. (s. 24)', 'Matematică Damian Iu. (s. 30)'],
                        ['Lecția 5 12.10 – 12.55', 'Matematică Damian Iu. (s. 23)', 'Limba și literatura română Iacubovschi M. (s. 30)', 'Geografie Cartaleanu E. (s. 22)', 'Geografie Cartaleanu E. (s. 22)', 'Matematică Damian Iu. (s. 30)'],
                        ['Lecția 6 13.25 – 14.10', 'Matematică Damian Iu. (s. 23)', 'Limba și literatura română Iacubovschi M. (s. 30)', 'Limba engleză , gr.1, Cociug S. (s. 21) Limba engleză , gr.2, Moșu A. (s. 6)', 'Chimie Bujor-Cobili C. (s. 34)', 'Fizică Solomonenco V. (s. 33)'],
                        ['Lecția 7 14.15 – 15.00', 'Fizică Solomonenco V. (s. 33)', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Educaţie pentru societate Demerji S. (s. 29)', 'Limba și literatura română Iacubovschi M. (s. 30)', 'Educaţie fizică Dumitrașcu A.'],
                        ['Lecția 8 15.10 – 15.55', 'Consultații Matematică Damian Iu. (s. 20)', 'Informatică , gr.1 15.05 – 16.20 Iurco O. (s. 24)', '', '', ''],
                    ],
                ],
                [
                    'label' => 'Clasa X U',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.15 – 09.00', '', 'Biologie Dorofeev A. (s. 21)', 'Educaţie fizică Dumitrașcu A.', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', ''],
                        ['Lecția 2 09.10 – 09.55', 'Fizică Solomonenco V. (s. 33)', 'Istoria românilor și universală Demerji S. (s. 32)', 'Limba și literatura română Iacubovschi M. (s. 30)', 'Limba și literatura română Iacubovschi M. (s. 32)', 'Dezvoltare personală Rudei R. (s. 14)'],
                        ['Lecția 3 10.10 – 10.55', 'Fizică Solomonenco V. (s. 33)', 'Istoria românilor și universală Demerji S. (s. 24)', 'Limba engleză Moșu A. (s. 21)', 'Limba engleză Moșu A. (s. 21)', 'Literatura universală Iacubovschi M. (s. 6)'],
                        ['Lecția 4 11.10 – 11.55', 'Limba și literatura română Iacubovschi M. (s. 19)', 'Geografie Cartaleanu E. (s. 22)', 'Matematică Damian Iu. (s. 20)', 'Educaţie fizică Dumitrașcu A.', 'Geografie Cartaleanu E. (s. 22)'],
                        ['Lecția 5 12.10 – 12.55', 'Limba engleză Moșu A. (s. 34)', 'Educaţie pentru societate Demerji S. (s. 6)', 'Matematică Damian Iu. (s. 20)', 'Limba și literatura română Iacubovschi M. (s. 30)', 'Informatică Iurco O. (s. 24)'],
                        ['Lecția 6 13.25 – 14.10', '', 'Chimie Bujor-Cobili C. (s. 4)', 'Istoria românilor și universală Demerji S. (s. 29)', '', 'Matematică Damian Iu. (s. 20)'],
                        ['Lecția 7 14.15 – 15.00', '', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Limba și literatura română Iacubovschi M. (s. 30)', '', ''],
                    ],
                ],
                [
                    'label' => 'Clasa XI R',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.15 – 09.00', 'Fizică Solomonenco V. (s. 33)', 'Istoria românilor și universală Demerji S. (s. 19)', 'Chimie Bujor-Cobili C. (s. 34)', '', ''],
                        ['Lecția 2 09.10 – 09.55', 'Limba engleză , gr.1, Cociug S. (s. 21) Limba engleză , gr.2, Moșu A. (s. 6)', 'Matematică Pascaru I. (s. 24)', 'Chimie Bujor-Cobili C. (s. 34)', 'Biologie Dorofeev A. (s. 20)', 'Matematică Pascaru I. (s. 23)'],
                        ['Lecția 3 10.10 – 10.55', 'Limba și literatura română Rotaru E. (s. 20)', 'Geografie Cartaleanu E. (s. 22)', 'Dezvoltare personală Cociug S. (s. 23)', 'Fizică Solomonenco V. (s. 33)', 'Geografie Cartaleanu E. (s. 22)'],
                        ['Lecția 4 11.10 – 11.55', 'Limba și literatura română Rotaru E. (s. 20)', 'Biologie Dorofeev A. (s. 20)', 'Educaţie fizică Dumitrașcu A.', 'Fizică Solomonenco V. (s. 33)', 'Limba și literatura română Rotaru E. (s. 19)'],
                        ['Lecția 5 12.10 – 12.55', 'Educaţie fizică Dumitrașcu A.', 'Biologie Dorofeev A. (s. 20)', 'Matematică Pascaru I. (s. 34)', 'Limba engleză , gr.1, Cociug S. (s. 21) Limba engleză , gr.2, Moșu A. (s. 19)', 'Limba și literatura română Rotaru E. (s. 19)'],
                        ['Lecția 6 13.25 – 14.10', 'Matematică Pascaru I. (s. 36)', 'Istoria românilor și universală Demerji S. (s. 19)', 'Matematică Pascaru I. (s. 27)', 'Limba germană Arhip S. (s. 32)', 'Informatică Iurco O. (s. 24)'],
                        ['Lecția 7 14.15 – 15.00', 'Consultații Matematică Damian Iu. (s. 20)', '', 'Limba engleză , gr.1, Cociug S. (s. 21) Limba engleză , gr.2, Moșu A. (s. 6)', 'Limba germană Arhip S. (s. 32)', 'Educaţie pentru societate Demerji S. (s. 29)'],
                        ['Lecția 8 15.10 – 15.55', '', '', '', '', 'Informatică gr.1 / gr.2 15.05 – 16.20 Iurco O. (s. 24)'],
                    ],
                ],
                [
                    'label' => 'Clasa XI U',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.15 – 09.00', 'in curand', '', '', '', ''],
                        ['Lecția 2 09.10 – 09.55', 'in curand', '', '', '', ''],
                        ['Lecția 3 10.10 – 10.55', 'in curand', '', '', '', ''],
                        ['Lecția 4 11.10 – 11.55', 'in curand', '', '', '', ''],
                        ['Lecția 5 12.10 – 12.55', 'in curand', '', '', '', ''],
                        ['Lecția 6 13.25 – 14.10', 'in curand', '', '', '', ''],
                        ['Lecția 7 14.15 – 15.00', 'in curand', '', '', '', ''],
                        ['Lecția 8 15.10 – 15.55', 'in curand', '', '', '', ''],
                    ],
                ],
                [
                    'label' => 'Clasa XII R',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.15 – 09.00', '', '', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Educaţie pentru sănătate Dorofeev A. (s. 22)', 'Pregătire pentru BAC Geografie Cartaleanu E. (s. 22)'],
                        ['Lecția 2 09.10 – 09.55', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Limba și literatura română Rotaru E. (s. 30)', 'Matematică Pascaru I. (s. 36)', 'Limba și literatura română Rotaru E. (s. 30)', 'Pregătire pentru BAC Limba și literatura română Rotaru E. (s. 30)'],
                        ['Lecția 3 10.10 – 10.55', 'Matematică Pascaru I. (s. 34)', 'Limba și literatura română Rotaru E. (s. 30)', 'Pregătire pentru BAC Matematică Pascaru I. (s. 36)', 'Limba și literatura română Rotaru E. (s. 30)', 'Matematică Pascaru I. (s. 23)'],
                        ['Lecția 4 11.10 – 11.55', 'Matematică Pascaru I. (s. 34)', 'Istoria românilor și universală Demerji S. (s. 26)', 'Dezvoltare personală Pascaru I. (s. 36)', 'Biologie Dorofeev A. (s. 29)', 'Matematică Pascaru I. (s. 24)'],
                        ['Lecția 5 12.10 – 12.55', 'Fizică Solomonenco V. (s. 33)', 'Chimie Bujor-Cobili C. (s. 34)', 'Educaţie fizică Dumitrașcu A.', 'Biologie Dorofeev A. (s. 29)', 'Geografie Cartaleanu E. (s. 22)'],
                        ['Lecția 6 13.25 – 14.10', 'Fizică Solomonenco V. (s. 33)', 'Biologie Dorofeev A. (s. 34)', 'Chimie Bujor-Cobili C. (s. 34)', 'Fizică Solomonenco V. (s. 33)', 'Chimie Bujor-Cobili C. (s. 34)'],
                        ['Lecția 7 14.15 – 15.00', 'Istoria românilor și universală Demerji S. (s. 29)', 'Limba engleză , gr.1, Cociug S. (s. 21) Limba engleză , gr.2, Moșu A. (s. 6)', 'Pregătire pentru BAC Chimie Bujor-Cobili C. (s. 34)', 'Limba engleză , gr.1, Cociug S. (s. 21) Limba engleză , gr.2, Moșu A. (s. 6)', 'Fizică Solomonenco V. (s. 33)'],
                        ['Lecția 8 15.10 – 15.55', 'Informatică , gr.1 15.05 – 16.20 Iurco O. (s. 24)', 'Limba engleză , gr.1, Cociug S. (s. 21) Limba engleză , gr.2, Moșu A. (s. 6)', '', 'Informatică , gr.2 15.05 – 16.20 Iurco O. (s. 24)', 'Educaţie pentru societate Demerji S. (s. 29)'],
                    ],
                ],
                [
                    'label' => 'Clasa XII U',
                    'headers' => ['', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri'],
                    'rows' => [
                        ['Lecția 1 08.15 - 09.00', 'Pregătire pentru BAC Chimie Bujor-Cobili C. (s. 34)', '', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', '', 'Pregătire pentru BAC Geografie Cartaleanu E. (s. 22)'],
                        ['Lecția 2 09.10 - 09.55', 'Limba franceză , Golban O. (s. 28) Limba germană , Arhip S. (s. 32)', 'Matematică Damian Iu. (s. 20)', 'Limba engleză Cociug S. (s. 21)', 'Istoria românilor și universală Demerji S. (s. 29)', 'Informatică Iurco O. (s. 24)'],
                        ['Lecția 3 10.10 - 10.55', 'Dezvoltare personală Demerji S. (s. 21)', 'Matematică Damian Iu. (s. 20)', 'Istoria românilor și universală Demerji S. (s. 20)', 'Biologie Dorofeev A. (s. 34)', 'Limba și literatura română Rotaru E. (s. 21)'],
                        ['Lecția 4 11.10 - 11.55', 'Limba engleză Cociug S. (s. 21)', 'Literatura universală Rotaru E. (s. 34)', 'Geografie Cartaleanu E. (s. 32)', 'Limba și literatura română Rotaru E. (s. 20)', 'Educaţie pentru societate Demerji S. (s. 29)'],
                        ['Lecția 5 12.10 - 12.55', 'Limba și literatura română Rotaru E. (s. 20)', 'Limba engleză Cociug S. (s. 21)', 'Educaţie fizică Dumitrașcu A.', 'Istoria românilor și universală Demerji S. (s. 20)', 'Chimie Bujor-Cobili C. (s. 34)'],
                        ['Lecția 6 13.25 - 14.10', 'Limba și literatura română Rotaru E. (s. 20)', 'Fizică Solomonenco V. (s. 33)', 'Matematică Damian Iu. (s. 20)', 'Educaţie ecologică Dorofeev A. (s. 22)', 'Limba și literatura română Rotaru E. (s. 21)'],
                        ['Lecția 7 14.15 - 15.00', 'Fizică Solomonenco V. (s. 33)', '', '', 'Literatura universală Rotaru E. (s. 22)', ''],
                        ['Lecția 8 15.10 - 15.55', 'Pregătire pentru BAC Istoria românilor și universală Demerji S. (s. 29)', '', '', 'Pregătire pentru BAC Limba și literatura română Rotaru E. (s. 22)', ''],
                    ],
                ],
            ],
            'orarul-sunetelor' => [
                [
                    'label' => 'Orarul sunetelor: clasele primare',
                    'headers' => ['Activitate', 'Interval de timp'],
                    'rows' => [
                        ['Lecția 1', '08.00 - 08.30'],
                        ['Dejun cl I', '08.30 - 08.50'],
                        ['Pauză', '08.50 - 09.05'],
                        ['Lecția 2', '09.05 - 09.50'],
                        ['Pauză', '09.50 - 10.10'],
                        ['Lecția 3', '10.10 - 10.55'],
                        ['Pauză', '10.55 - 11.15'],
                        ['Lecția 4', '11.15 - 12.00'],
                        ['Prânz cl I', '12.00 - 12.20'],
                        ['Lecția 5', '12.20 - 13.05'],
                        ['PJ', '13.05 - 14.05'],
                        ['PTA 1', '14.05 - 14.50'],
                        ['Pauză', '14.50 - 15.00'],
                        ['PTA 2', '15.00 - 15.45'],
                    ],
                ],
                [
                    'label' => 'Clasele gimnaziale și liceale (V – XII)',
                    'headers' => ['Activitate', 'Interval de timp'],
                    'rows' => [
                        ['Lecția 1', '08.15 - 09.00'],
                        ['Pauză', '09.00 - 09.10'],
                        ['Pauză, Dejun', '09.55 - 10.10'],
                        ['Lecția 2', '09.10 - 09.55'],
                        ['Lecția 3', '10.10 - 10.55'],
                        ['Pauză', '10.55 - 11.10'],
                        ['Lecția 4', '11.10 - 11.55'],
                        ['Pauză', '11.55 - 12.10'],
                        ['Lecția 5', '12.10 - 12.55'],
                        ['Pauză, Prânz', '12.55 - 13.25'],
                        ['Lecția 6', '13.25 - 14.10'],
                        ['Pauză', '14.10 - 14.15'],
                        ['Lecția 7', '14.15 - 15.00'],
                        ['Pauză', '15.00 - 15.10'],
                        ['Lecția 8', '15.10 - 15.55'],
                    ],
                ],
            ],
            'orarul-examenelor' => [
                [
                    'label' => 'Orarul examenelor finale',
                    'headers' => ['Nr. ctr.', 'Proba de evaluare', 'Data'],
                    'rows' => [
                        ['1.', 'Matematica', '14 mai 2026 (joi)'],
                        ['2.', 'Limba română', '19 mai 2026 (marți)'],
                    ],
                ],
                [
                    'label' => 'Orarul examenelor finale',
                    'headers' => ['Nr. ctr.', 'Proba de evaluare', 'Data'],
                    'rows' => [
                        ['1.', 'Istoria românilor și universală', '04 iunie 2026 (joi)'],
                        ['2.', 'Matematică', '08 iunie 2026 (luni)'],
                        ['3.', 'Limba română', '11 iunie 2026 (joi)'],
                    ],
                ],
                [
                    'label' => 'Orarul examenelor finale',
                    'headers' => ['Nr. ctr.', 'Discipline de examen', 'Data'],
                    'rows' => [
                        ['1.', 'Limba și literatura română', '05 iunie 2026 (vineri)'],
                        ['2.', 'Limba străină I (engleză)', '09 iunie 2026 (marți)'],
                        ['4.', 'Disciplina la solicitare', '16 iunie 2026 (marți)'],
                    ],
                ],
            ],
            'orarul-pretestarilor' => [
                [
                    'label' => 'Orarul pretestărilor',
                    'headers' => ['Nr. ctr.', 'Proba de evaluare', 'Data'],
                    'rows' => [
                        ['1.', 'Matematica', ''],
                        ['2.', 'Limba și literatura română', ''],
                        ['3.', 'Istoria românilor și universală', ''],
                    ],
                ],
                [
                    'label' => 'Orarul pretestărilor',
                    'headers' => ['Nr. ctr.', 'Proba de evaluare', 'Data'],
                    'rows' => [
                        ['1.', 'Limba și literatura română', ''],
                        ['2.', 'Limba engleză', ''],
                        ['3.', 'Disciplina de profil Matematică / Istoria românilor și universală', ''],
                        ['4.', 'Disciplina la solicitare', ''],
                    ],
                ],
            ],
            'orar-recuperari' => [
                [
                    'label' => 'Orar recuperări',
                    'headers' => ['Nr.', 'Disciplina de studiu', 'Clasa', 'Nr. de elevi cu program de recuperare', 'Cadru didactic', 'Intervalul de timp'],
                    'rows' => [
                        ['1.', 'Matematică', 'III L', '1', 'Lîsov D.', 'Luni, Miercuri 14.05 - 14.35'],
                        ['2.', 'Matematică', 'VII 2', '1', 'Cociurca N.', 'Joi, săptămâna impară 15.30 - 16.00'],
                        ['3.', 'Matematică', 'VIII 2', '1', 'Cociurca N.', 'Miercuri, săptămâna pară 14.35 - 15.05'],
                        ['4.', 'Matematică', 'IX 1', '1', 'Cociurca N.', 'Joi 14.35 - 15.05'],
                        ['5.', 'Limba română', 'III L', '1', 'Lîsov D.', 'Luni, Miercuri 15.00 - 15.30'],
                        ['6.', 'Limba și literatura română', 'VI 2', '2', 'Railean V.', 'Marți 14.35 - 15.05'],
                        ['7.', 'Limba engleză', 'III L', '1', 'Roșcovanu V.', 'Marți, Joi 14.05 - 14.35'],
                        ['8.', 'Limba engleză', 'V 2', '5', 'Pascaru M.', 'Luni 14.35 - 15.05'],
                        ['9.', 'Limba engleză', 'VI 2', '1', 'Buga A.', 'Vineri, săptămâna pară 13.45 - 14.15'],
                        ['10.', 'Limba engleză', 'VII 2', '1', 'Balan T.', 'Luni 15.25 - 15.55'],
                        ['11.', 'Limba engleză', 'X U', '1', 'Balan T.', 'Luni 15.55 - 16.25'],
                    ],
                ],
            ],
            'sedintele-cu-parintii' => [
                [
                    'label' => 'Ședințele cu părinții',
                    'headers' => ['Nr.', 'Clasa', 'Data', 'Sala', 'Ora', 'Diriginte'],
                    'rows' => [
                        ['1.', '3-C', 'Luni 04.05.2026', '11', '16:00', 'Proaspăt A.'],
                        ['2.', '3-L', 'Luni 04.05.2026', '10', '16:00', 'Lavric E.O.'],
                        ['3.', '1-C', 'Marți 05.05.2026', '15', '16:00', 'Colesnic L.'],
                        ['4.', '2-L', 'Marți 05.05.2026', '3', '16:00', 'Lîsov D.'],
                        ['5.', '1-I', 'Joi 07.05.2026', '16', '16:00', 'Cocu I.'],
                        ['6.', '2-T', 'Joi 07.05.2026', '8', '16:00', 'Tricolici O.'],
                        ['7.', '4-L', 'Vineri 22.05.2026', '18', '16:00', 'Lungu E.'],
                        ['8.', '4-N', 'Vineri 22.05.2026', '18', '16:00', 'Nasoila L.'],
                        ['9.', '4-S', 'Vineri 22.05.2026', '18', '16:00', 'Căldare O.'],
                    ],
                ],
                [
                    'label' => 'Ședințele cu părinții',
                    'headers' => ['Nr.', 'Clasa', 'Data', 'Sala', 'ora', 'Diriginte'],
                    'rows' => [
                        ['1.', 'V.1', 'Luni 04.05.2026', '39', '16:30', 'Cociurca N.'],
                        ['2.', 'V.2', 'Marți 05.05.2026', '33', '16:30', 'Căruntu N.'],
                        ['3.', 'VI.2', 'Marți 05.05.2026', '23', '16:30', 'Cociurca N.'],
                        ['4.', 'VII.1', 'Miercuri 06.05.2026', '24', '16:30', 'Iurco O.'],
                        ['5.', 'VII.2', 'Miercuri 06.05.2026', '4', '16:30', 'Moșu A.'],
                        ['6.', 'VI.1', 'Joi 07.05.2026', '33', '16:30', 'Arhip S.'],
                        ['7.', 'VIII.2', 'Joi 07.05.2026', '19', '16:30', 'Russu I.'],
                        ['8.', 'VIII.1', 'Vineri 08.05.2026', '19', '16:30', 'Pascaru M.'],
                        ['9.', 'IX.1', 'Luni 11.05.2026', '33', '16:30', 'Golban O.'],
                        ['10.', 'IX.2', 'Luni 11.05.2026', '20', '16:30', 'Buga A.'],
                    ],
                ],
                [
                    'label' => 'Ședințele cu părinții',
                    'headers' => ['Nr.', 'Clasa', 'Data', 'Sala', 'Ora', 'Diriginte'],
                    'rows' => [
                        ['1.', 'X-R', 'Luni 04.05.2026', '29', '16.30', 'Demerji S.'],
                        ['2.', 'X-U', 'Miercuri 06.05.2026', '29', '16.30', 'Demerji S.'],
                        ['3.', 'XI-R', 'Miercuri 06.05.2026', '34', '16.30', 'Bujor-Cobili C.'],
                        ['4.', 'XI-U', 'Vineri 08.05.2026', '30', '16.30', 'Rudei R.'],
                    ],
                ],
            ],
            'orarul-cpae' => [
                [
                    'label' => 'Orarul CPAE',
                    'headers' => ['Nr.', 'Tipul activității', 'Responsabil', 'Ziua desfășurării', 'Ora desfășurării'],
                    'rows' => [
                        ['1.1', 'Arta vorbirii I-II', 'Cătălina Varanița', 'Marți Joi', '16.35-17.15'],
                        ['1.2', 'Arta vorbirii III-IV', 'Cătălina Varanița', 'Marți Joi', '15.50 - 16.30'],
                        ['2.1', 'Micii antreprenori, cl. IV', 'Irina Ghelbur', 'Miercuri', '15.50 - 16.30'],
                        ['2.2', 'Micii antreprenori, cl. V-VIII', 'Irina Ghelbur', 'Miercuri', '14.15 - 15.00 15.05 - 15.50'],
                        ['3.1', 'Dansuri I-II', 'Nicoleta Fidorov', 'Marți Joi', '15.50 - 16.30'],
                        ['3.2', 'Dansuri III-IV', 'Nicoleta Fidorov', 'Marți Joi', '16.35 - 17.15'],
                        ['4.1', 'Șahul I-II', 'Alexandr Dumitrașcu', 'Marți Joi', '16.35 - 17.15 15.50 - 16.30'],
                        ['4.2', 'Șahul III-IV', 'Alexandr Dumitrașcu', 'Marți Joi', '15.50 - 16.30 16.35 - 17.15'],
                        ['4.3', 'Șahul V-VII', 'Alexandr Dumitrașcu', 'Marți Joi', '14.20 - 15.15'],
                        ['5.1', 'Corul I-II', 'Vasile Ungureanu', 'Marți Miercuri', '15.50 - 16.30 16.35 - 17.15'],
                        ['5.2', 'Corul III-IV', 'Vasile Ungureanu', 'Marți Miercuri', '16.35 - 17.15 15.50 - 16.30'],
                        ['6.1', 'Fotbal I-II', 'Alexandr Dumitrașcu', 'Luni Miercuri', '15.50 - 16.30 16.35 - 17.15'],
                        ['6.2', 'Fotbal III-IV', 'Alexandr Dumitrașcu', 'Marți Miercuri', '16.35 - 17.15 15.50 - 16.30'],
                        ['6.3', 'Fotbal V-VI', 'Alexandr Dumitrașcu', 'Marți Miercuri', '14.20 - 15.15'],
                        ['7.1', 'Pictura I-II', 'Irina Bardița', 'Marți Vineri', '16.35 - 17.15 15.50 - 16.30'],
                        ['7.2', 'Pictura III-IV', 'Irina Bardița', 'Marți Vineri', '15.50 - 16.30 16.35 - 17.15'],
                        ['7.3', 'Pictura V-VIII', 'Irina Bardița', 'Marți Vineri', '14.20 - 15.15'],
                        ['8.1', 'Exploratori media, cl. IV', 'Irina Ghelbur', 'Luni', '15.50 - 16.30'],
                        ['8.2', 'Exploratori media, V - VII', 'Irina Ghelbur', 'Luni', '14.15 - 15.00 15.05 - 15.50'],
                        ['9.', 'Robotica I - IV', 'Daniela Voitcovschi', 'Marți Miercuri', '14.35 - 15.05 15.10 - 15.45 15.50 - 16.25 16.30 - 17.05'],
                        ['10.', 'Micile talente I-IV', 'Tricolici Olga', 'Joi', '15.45 - 16.30 16.35 - 17.15'],
                    ],
                ],
            ],
            'orarul-ess' => [
                [
                    'label' => 'Clasele liceale',
                    'headers' => ['Data, ziua', 'Clasa', 'Disciplina', 'Ora desfășurării'],
                    'rows' => [
                        ['11 decembrie 2025, JOI', '10R', 'Limba și literatura română', '09.10 - 10.40'],
                        ['10U', 'Limba și literatura română'],
                        ['11R', 'Limba engleză'],
                        ['11U', 'Limba engleză'],
                        ['12R', 'Limba și literatura română'],
                        ['15 decembrie 2025, LN', '10R', 'Matematică', '09.10 - 10.40'],
                        ['10U', 'Istoria românilor și universală'],
                        ['11R', 'Matematică'],
                        ['11U', 'Istoria românilor și universală'],
                        ['12R', 'Matematică'],
                        ['18 decembrie 2025, JOI', '10R', 'Disciplina la solicitare', '09.10 - 10.40'],
                        ['10U', 'Disciplina la solicitare'],
                        ['11R', 'Disciplina la solicitare'],
                        ['11U', 'Disciplina la solicitare'],
                        ['12R', 'Disciplina la solicitare'],
                    ],
                ],
                [
                    'label' => 'Clasele gimnaziale',
                    'headers' => ['Data, ziua', 'Clasa', 'Disciplina', 'Ora desfășurării'],
                    'rows' => [
                        ['15 decembrie 2025, LUNI', '5.1', 'Limba și literatura română', '09.10 - 09.55'],
                        ['5.2', 'Limba și literatura română'],
                        ['6.1', 'Limba engleză'],
                        ['6.2', 'Limba engleză'],
                        ['7.1', 'Istoria românilor și universală'],
                        ['7.2', 'Istoria românilor și universală'],
                        ['8.1', 'Biologie'],
                        ['8.2', 'Biologie'],
                        ['9.1', 'Matematică'],
                        ['9.2', 'Matematică'],
                        ['7.1', 'Matematică', '10.10 - 10.55'],
                        ['7.2', 'Matematică'],
                        ['8.1', 'Limba și literatura română'],
                        ['8.2', 'Limba și literatura română'],
                        ['9.1', 'Limba engleză'],
                        ['9.2', 'Limba engleză'],
                        ['16 decembrie 2025, MARȚI', '5.1', 'Limba engleză', '09.10 - 09.55'],
                        ['5.2', 'Limba engleză'],
                        ['6.1', 'Matematică'],
                        ['6.2', 'Matematică'],
                        ['7.1', 'Biologie'],
                        ['7.2', 'Biologie'],
                        ['8.1', 'Fizică'],
                        ['8.2', 'Fizică'],
                        ['9.1', 'Geografie'],
                        ['9.2', 'Geografie'],
                        ['9.1', 'Istoria românilor și universală', '10.10 - 10.55'],
                        ['9.2', 'Istoria românilor și universală'],
                        ['17 decembrie 2025, MIERCURI', '6.1', 'Limba și literatura română', '09.10 - 09.55'],
                        ['6.2', 'Limba și literatura română'],
                        ['7.1', 'Limba engleză'],
                        ['7.2', 'Limba engleză'],
                        ['8.1', 'Istoria românilor și universală'],
                        ['8.2', 'Istoria românilor și universală'],
                        ['9.1', 'Biologie'],
                        ['9.2', 'Biologie'],
                        ['8.1', 'Chimie', '10.10 - 10.55'],
                        ['8.2', 'Chimie'],
                        ['9.1', 'Fizică'],
                        ['9.2', 'Fizică'],
                        ['9.1, grupa 1', 'Informatică', '14.15 - 15.00'],
                        ['18 decembrie 2025, JOI', '5.1', 'Matematică', '09.10 - 09.55'],
                        ['5.2', 'Matematică'],
                        ['6.1', 'Istoria românilor și universală'],
                        ['6.2', 'Istoria românilor și universală'],
                        ['7.1', 'Limba și literatura română'],
                        ['7.2', 'Limba și literatura română'],
                        ['8.1', 'Matematică'],
                        ['8.2', 'Matematică'],
                        ['9.1', 'Limba și literatura română'],
                        ['9.2', 'Limba și literatura română'],
                        ['7.1', 'Fizică', '10.10 - 10.55'],
                        ['7.2', 'Fizică'],
                        ['8.1', 'Limba engleză'],
                        ['8.2', 'Limba engleză'],
                        ['9.1', 'Chimie'],
                        ['9.2', 'Chimie'],
                        ['9.2, grupa 1', 'Informatică', '12.10 - 12.55'],
                        ['19 decembrie 2025, VINERI', '9.1, 9.2, grupa 2', 'Informatică', '08.15 - 09.00'],
                    ],
                ],
                [
                    'label' => 'Clasele liceale',
                    'headers' => ['Nr. ctr.', 'Clasa', 'Disciplina', 'Ora desfășurării'],
                    'rows' => [
                        ['1.', '10R', 'Limba și literatura română', '09.35 – 11.05'],
                        ['2.', '10U', 'Limba și literatura română', '09.35 – 11.05'],
                        ['3.', '11R', 'Limba străină I (engleză)', '09.35 – 11.05'],
                        ['4.', '11U', 'Limba străină I (engleză)', '09.35 – 11.05'],
                        ['5.', '12R', 'Matematică', '09.35 – 11.05'],
                        ['6.', '12U', 'Istoria românilor și universală', '09.35 – 11.05'],
                    ],
                ],
                [
                    'label' => 'Clasele gimnaziale',
                    'headers' => ['Nr. ctr.', 'Clasa', 'Disciplina', 'Ora desfășurării'],
                    'rows' => [
                        ['1.', '5.1', 'Limba engleză', '09.35 – 10.20'],
                        ['2.', '5.2', 'Limba engleză', '09.35 – 10.20'],
                        ['3.', '6.1', 'Istoria românilor și universală', '09.35 – 10.20'],
                        ['4.', '6.2', 'Istoria românilor și universală', '09.35 – 10.20'],
                        ['5.', '7.1', 'Matematică', '09.35 – 10.20'],
                        ['6.', '7.2', 'Matematică', '09.35 – 10.20'],
                        ['7.', '8.1', 'Limba și literatura română', '09.35 – 10.20'],
                        ['8.', '8.2', 'Limba și literatura română', '09.35 – 10.20'],
                        ['9.', '9.1', 'Limba engleză', '09.35 – 10.20'],
                        ['10.', '9.2', 'Limba engleză', '09.35 – 10.20'],
                    ],
                ],
                [
                    'label' => 'Clasele gimnaziale',
                    'headers' => ['Nr. ctr.', 'Clasa', 'Disciplina', 'Ora desfășurării'],
                    'rows' => [
                        ['1.', '7.1', 'Limba și literatura română', '09.35 – 10.20'],
                        ['2.', '7.2', 'Limba și literatura română', '09.35 – 10.20'],
                        ['3.', '8.1', 'Matematică', '09.35 – 10.20'],
                        ['4.', '8.2', 'Matematică', '09.35 – 10.20'],
                        ['5.', '9.1', 'Geografie', '09.35 – 10.20'],
                        ['6.', '9.2', 'Geografie', '09.35 – 10.20'],
                        ['7.', '8.1', 'Biologie', '10.35 – 11.20'],
                        ['8.', '8.2', 'Biologie', '10.35 – 11.20'],
                        ['9.', '9.1', 'Fizică', '10.35 – 11.20'],
                        ['10.', '9.2', 'Fizică', '10.35 – 11.20'],
                    ],
                ],
                [
                    'label' => 'Clasele liceale',
                    'headers' => ['Nr. ctr.', 'Clasa', 'Disciplina', 'Ora desfășurării'],
                    'rows' => [
                        ['1.', '10R', 'Fizică (3 el) Biologie (1 el) Chimie (17 el) Informatică (2 el)', '09.35 – 10.30'],
                        ['2.', '10U', 'Biologie (7 el) Matematică (2 el) Chimie (2 el)', '09.00 – 10.30'],
                        ['3.', '11R', 'Geografie (2 el) Chimie (9 el) Biologie (8 el) Fizică (3 el) Istorie (4 el)', '09.35 – 10.30'],
                        ['4.', '11U', 'Biologie (8 el) Geografie (3 el) Chimie (2 el) Matematică (4 el)', '09.00 – 10.30'],
                        ['5.', '12R', 'Limba engleză (3 el) Chimie (2 el) Informatică (3 el) Istorie (2 el) Geografie (5 el) Biologie (2 el) Fizică (1 el)', '09.35 – 10.30'],
                        ['6.', '12U', 'Limba engleză (13 el) Chimie (6 el) Geografie (2 el) Matematică (1 el)', '09.00 – 10.30'],
                    ],
                ],
                [
                    'label' => 'Clasele gimnaziale',
                    'headers' => ['Nr. ctr.', 'Clasa', 'Disciplina', 'Ora desfășurării'],
                    'rows' => [
                        ['1.', '9.2 gr1', 'GR 1, Informatică', '08.35 – 09.20'],
                        ['2.', '5.1', 'Matematică', '09.35 – 10.20'],
                        ['3.', '5.2', 'Matematică', '09.35 – 10.20'],
                        ['4.', '6.1', 'Limba engleză', '09.35 – 10.20'],
                        ['5.', '6.2', 'Limba engleză', '09.35 – 10.20'],
                        ['6.', '7.1', 'Limba engleză', '09.35 – 10.20'],
                        ['7.', '7.2', 'Limba engleză', '09.35 – 10.20'],
                        ['8.', '8.1', 'Chimie', '09.35 – 10.20'],
                        ['9.', '8.2', 'Chimie', '09.35 – 10.20'],
                        ['10.', '9.1', 'Istoria românilor și universală', '09.35 – 10.20'],
                        ['11.', '9.2', 'Istoria românilor și universală', '09.35 – 10.20'],
                        ['12.', '9.1, 9.2, gr 3', 'GR 3, Informatică', '13.45 – 14.30'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @return list<array{label: string, headers: list<string>, rows: list<list<string>>}>
     */
    public static function for(string $name): array
    {
        return self::all()[$name] ?? [];
    }
}
